feat(forge): Add test matching support to foundry.toml
foundry-rs/foundry pull request #1378
Opened 2022-04-21 17:19 UTC by lattejed

## Motivation

https://github.com/foundry-rs/foundry/issues/1346

`test` matching flags should be supported in `foundry.toml` so complex matching setups can be stored and enabled with different config profiles.

## Solution

Add the matching flags from `test` to the `Config` file, swapping kebab for snake case, e.g., `--match-test` is `match_test` in `foundry.toml`.

`Config` entries are merged with `test` flags. If both config entry and flag are present, the flag takes precedence.

Regex doesn't implement PartialEq (required for `Config` testing) so a wrapper type was added, `serde` was setup to deal with this

2022-04-21 19:11 UTC, onbjerg approved these changes
LGTM but I want @mattsse to take a look as well

2022-04-22 08:29 UTC, lattejed commented
A couple of things I don't like here:

1. Wrapping `Regex` to provide `PartialEq`. The problem is `derive` is all or nothing, so using `Regex` means implementing `PartialEq` for the entire `Config` struct by hand. Equality is needed for testing.
2. Manually merging `Filter` and `Config`. I'm not sure if it's possible to make `Figment` work in this case since the members are different types. `Figment` is pretty light on docs.

2022-04-22 11:50 UTC, mattsse requested changes
fantastic! only smol nits

while the regex wrapper is a bit unfortunate, it's the best solution here.

mind also adding a `forge_test!` for that, see `config.rs` in the cli/tests folder for reference, something like this but for the path options:

```rust
forgetest!(can_set_gas_price, |prj: TestProject, mut cmd: TestCommand| {
    cmd.set_current_dir(prj.root());

    // explicitly set gas_price
    let config = Config { gas_price: 1337, ..Default::default() };
    prj.write_config(config);

    let config = cmd.config();

    assert_eq!(config.gas_price, 1337);

    let config = prj.config_from_output(["--gas-price", "300"]);
    assert_eq!(config.gas_price, 300);
});
```

2022-04-22 11:50 UTC, mattsse commented on cli/src/cmd/forge/test.rs
> +        let mut filter = self.clone();
since this clones regardless, should the function instead accept `self`?

2022-04-22 14:37 UTC, mattsse commented on cli/src/cmd/forge/test.rs
> +        let mut filter = self.clone();
I see, makes sense.
naming is fine :)

2022-04-23 10:35 UTC, lattejed commented
@mattsse good call on the test. There's actually a bug with `Glob` round-tripping a config to disk and back. 

Do you know who did the heavy lifting for `Config` /  `Figment`? I want to validate some assumptions.

2022-04-23 11:29 UTC, mattsse commented
> @mattsse good call on the test. There's actually a bug with `Glob` round-tripping a config to disk and back.
> 
> Do you know who did the heavy lifting for `Config` / `Figment`? I want to validate some assumptions.

shoot :)

2022-04-23 16:07 UTC, lattejed commented
Ah, I found it. `Glob` doesn't explicitly handle `Option<Glob>` in it's `serde` impl

2022-04-23 16:58 UTC, mattsse commented
good to merge @lattejed ?

2022-04-23 17:01 UTC, lattejed commented
Should be good to go @mattsse

2022-04-23 17:03 UTC, mattsse commented
fantastic, ty!

2022-04-23 17:03 UTC, mattsse approved these changes

2022-04-23 17:04 UTC, merged