replace dapphub/ds-test with forge-std
foundry-rs/foundry pull request #1409
Opened 2022-04-25 03:03 UTC by shawnharmsen

First time contributor starting with the simplest issues.

Replace dapphub/ds-test library with forge-std

## Motivation

## Solution

Install and see lib
```bash
➜  foundry git:(master) ✗ cargo install --path ./cli --bins --locked --force

➜  test tree            
.
└── hello_foundry
    ├── foundry.toml
    ├── lib
    │   └── forge-std
    │       ├── LICENSE-APACHE
    │       ├── LICENSE-MIT
    │       ├── README.md
    │       ├── lib
    │       │   └── ds-test
    │       │       ├── LICENSE
    │       │       ├── Makefile
    │       │       ├── default.nix
    │       │       ├── demo
    │       │       │   └── demo.sol
    │       │       └── src
    │       │           └── test.sol
```

2022-04-25 03:27 UTC, onbjerg approved these changes
LGTM, but you also need to update the tests, specifically the ones in `cli/tests/it/cmd.rs` that rely on `ds-test` being present :smile:

2022-04-25 03:53 UTC, shawnharmsen commented
Whoops thank you for that will keep checking.
Also fixed my local git issue with maple_loan

```bash
foundry git:(master) ✗ cargo test --all --all-features -p foundry-cli --test it
    Finished test [unoptimized] target(s) in 0.42s
     Running tests/it/main.rs (target/debug/deps/it-fbfddc622f65f44f)

running 9 tests
test integration::drai ... ok
test integration::gunilev ... ok
test integration::multicall ... ok
test integration::stringutils ... ok
test integration::lil_web3 ... ok
test integration::lootloose ... ok
test integration::solmate ... ok
test integration::geb ... ok
test integration::maple_loan ... ok

test result: ok. 9 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 46.62s
```

2022-04-25 05:14 UTC, shawnharmsen commented
I apologize but I'm having some trouble here, I will try to come back with fresh eyes

- I see that ci shows two errors  
```
---- config::can_override_config stdout ----
thread 'config::can_override_config' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', cli/tests/it/config.rs:127:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- cmd::can_init_vscode stdout ----
thread 'cmd::can_init_vscode' panicked at 'assertion failed: `(left == right)`
  left: `"forge-std/=lib/forge-std/src/\nds-test/=lib/forge-std/lib/ds-test/src/"`,
 right: `"forge-std/=lib/forge-std/src/"`', cli/tests/it/cmd.rs:131:5


failures:
    cmd::can_init_vscode
    config::can_override_config
```

- testing locally I'm getting 
    

```
➜  foundry git:(master) cargo test --locked --workspace --test '*'      
failures:

---- config::can_extract_config_values stdout ----
thread 'config::can_extract_config_values' panicked at 'assertion failed: `(left == right)`
  left: `Config { profile: Profile(Uncased { string: "default" }), src: "test-src", test: "test-test", out: "out-test", libs: ["lib-test"], remappings: [RelativeRemapping { name: "forge-std", path: RelativeRemappingPathBuf { parent: None, path: "lib/forge-std/" } }], libraries: ["src/DssSpell.sol:DssExecLib:0x8De6DDbCd5053d32292AAA0D2105A32d108484a6"], cache: true, cache_path: "test-cache", force: true, evm_version: Byzantium, gas_reports: ["Contract"], solc: Some(Local("custom-solc")), auto_detect_solc: false, offline: true, optimizer: false, optimizer_runs: 1000, optimizer_details: Some(OptimizerDetails { peephole: None, inliner: None, jumpdest_remover: None, order_literals: None, deduplicate: None, cse: None, constant_optimizer: None, yul: Some(false), yul_details: Some(YulDetails { stack_allocation: Some(true), optimizer_steps: None }) }), verbosity: 4, eth_rpc_url: Some("localhost"), etherscan_api_key: None, ignored_error_codes: [], test_pattern: None, test_pattern_inverse: None, contract_pattern: None, contract_pattern_inverse: None, path_pattern: None, path_pattern_inverse: None, fuzz_runs: 1000, ffi: true, sender: 0x00a329c0648769a73afac7f9381d08fb43dbea72, tx_origin: 0x00a329c0648769a73afac7f9f81e08fb43dbea72, initial_balance: 79228162514264337593543950335, block_number: 10, fork_block_number: Some(200), chain_id: Some(Id(9999)), gas_limit: GasLimit(99000000), gas_price: 999, block_base_fee_per_gas: 10, block_coinbase: 0x2cfa98b84225497203c294640c7cc14c79555a0e, block_timestamp: 10, block_difficulty: 10, block_gas_limit: Some(GasLimit(100)), memory_limit: 33554432, extra_output: [], extra_output_files: [], fuzz_max_local_rejects: 2000, fuzz_max_global_rejects: 100203, names: true, sizes: true, via_ir: true, rpc_storage_caching: StorageCachingConfig { chains: None, endpoints: Remote }, no_storage_caching: true, bytecode_hash: Ipfs, revert_strings: Some(Strip), sparse_mode: true, __root: RootPath("."), __non_exhaustive: () }`,
 right: `Config { profile: Profile(Uncased { string: "default" }), src: "test-src", test: "test-test", out: "out-test", libs: ["lib-test"], remappings: [RelativeRemapping { name: "forge-std", path: RelativeRemappingPathBuf { parent: None, path: "lib/forge-std/" } }], libraries: ["src/DssSpell.sol:DssExecLib:0x8De6DDbCd5053d32292AAA0D2105A32d108484a6"], cache: true, cache_path: "test-cache", force: true, evm_version: Byzantium, gas_reports: ["Contract"], solc: Some(Local("custom-solc")), auto_detect_solc: false, offline: true, optimizer: false, optimizer_runs: 1000, optimizer_details: Some(OptimizerDetails { peephole: None, inliner: None, jumpdest_remover: None, order_literals: None, deduplicate: None, cse: None, constant_optimizer: None, yul: Some(false), yul_details: Some(YulDetails { stack_allocation: Some(true), optimizer_steps: None }) }), verbosity: 4, eth_rpc_url: Some("localhost"), etherscan_api_key: Some("B6ZIKEH2JCCXJ6URFVSC27PK6TH2G74X2P"), ignored_error_codes: [], test_pattern: None, test_pattern_inverse: None, contract_pattern: None, contract_pattern_inverse: None, path_pattern: None, path_pattern_inverse: None, fuzz_runs: 1000, ffi: true, sender: 0x00a329c0648769a73afac7f9381d08fb43dbea72, tx_origin: 0x00a329c0648769a73afac7f9f81e08fb43dbea72, initial_balance: 79228162514264337593543950335, block_number: 10, fork_block_number: Some(200), chain_id: Some(Id(9999)), gas_limit: GasLimit(99000000), gas_price: 999, block_base_fee_per_gas: 10, block_coinbase: 0x2cfa98b84225497203c294640c7cc14c79555a0e, block_timestamp: 10, block_difficulty: 10, block_gas_limit: Some(GasLimit(100)), memory_limit: 33554432, extra_output: [], extra_output_files: [], fuzz_max_local_rejects: 2000, fuzz_max_global_rejects: 100203, names: true, sizes: true, via_ir: true, rpc_storage_caching: StorageCachingConfig { chains: None, endpoints: Remote }, no_storage_caching: true, bytecode_hash: Ipfs, revert_strings: Some(Strip), sparse_mode: true, __root: RootPath("."), __non_exhaustive: () }`', cli/tests/it/config.rs:99:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- config::can_override_config stdout ----
thread 'config::can_override_config' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', cli/tests/it/config.rs:127:5

---- cmd::can_init_vscode stdout ----
thread 'cmd::can_init_vscode' panicked at 'assertion failed: `(left == right)`
  left: `"forge-std/=lib/forge-std/src/\nds-test/=lib/forge-std/lib/ds-test/src/"`,
 right: `"forge-std/=lib/forge-std/src/"`', cli/tests/it/cmd.rs:131:5


failures:
    cmd::can_init_vscode
    config::can_extract_config_values
    config::can_override_config

test result: FAILED. 37 passed; 3 failed; 1 ignored; 0 measured; 0 filtered out; finished in 14.43s

```

2022-04-25 05:20 UTC, onbjerg commented
In the first one you need to change this line:

https://github.com/foundry-rs/foundry/blob/c1050cb5093fcb228c773561fc13d4bd6869d13f/cli/tests/it/config.rs#L127

to:

```rs
assert_eq!(profile.remappings.len(), 2);
```


Since Forge Std also ships with DSTest

For the second one, you need to change this line:

https://github.com/foundry-rs/foundry/blob/c1050cb5093fcb228c773561fc13d4bd6869d13f/cli/tests/it/cmd.rs#L131

to:

```rs
assert_eq!(content, "forge-std/=lib/forge-std/src/\nds-test/=lib/forge-std/lib/ds-test/src/");
```

For the same reason

2022-04-25 05:38 UTC, onbjerg commented
My apologies, the last one was the other way around :smile: So `ds-test/=lib/forge-std/lib/ds-test/src/\nforge-std/=lib/forge-std/src/`

2022-04-25 05:40 UTC, shawnharmsen commented
Really appreciate the help.

locally getting below

```
---- config::can_override_config stdout ----
thread 'config::can_override_config' panicked at 'assertion failed: `(left == right)`
  left: `"forge-std/=lib/forge-std/src/"`,
 right: `"ds-test/=lib/forge-std/lib/ds-test/src/"`', cli/tests/it/config.rs:128:5


failures:
    config::can_extract_config_values
    config::can_override_config

test result: FAILED. 38 passed; 2 failed; 1 ignored; 0 measured; 0 filtered out; finished in 14.12s

error: test failed, to rerun pass '-p foundry-cli --test it'

```

do not have the ci error of 
```
---- cmd::can_init_vscode stdout ----
thread 'cmd::can_init_vscode' panicked at 'assertion failed: `(left == right)`
  left: `"ds-test/=lib/forge-std/lib/ds-test/src/\nforge-std/=lib/forge-std/src/"`,
 right: `"forge-std/=lib/forge-std/src/\nds-test/=lib/forge-std/lib/ds-test/src/"`', cli/tests/it/cmd.rs:131:5
```

2022-04-25 16:39 UTC, gakonst approved these changes

2022-04-25 19:21 UTC, gakonst requested changes
@shawnharmsen nice work! only needs a couple more changes to fix integration tests

2022-04-26 11:01 UTC, shawnharmsen commented
tyvm will work on it more this week after i grok some of my rusty rust

2022-04-26 14:42 UTC, gakonst approved these changes
lgtm! thanks for the contribution!

2022-04-26 14:42 UTC, merged