fix(cast): add artifact support to cast inspect
foundry-rs/foundry pull request #1451
Opened 2022-04-29 03:55 UTC by ncitron

## Motivation
Addresses #1439

## Solution
If the json file has an `abi` key, we know it is an artifact rather than a plain abi file and handle it appropriately.

2022-04-29 07:36 UTC, mattsse requested changes
ty, smol nit to prevent the rather large clone

2022-04-29 07:36 UTC, mattsse commented on cast/src/lib.rs
> +                let json = if !json["abi"].is_null() { json["abi"].clone() } else { json };
```suggestion
                let mut json: serde_json::Value = serde_json::from_str(&file)?;
                let json = if !json["abi"].is_null() { json.take("abi") } else { json };
```

2022-04-30 15:56 UTC, onbjerg approved these changes

2022-04-30 16:00 UTC, ncitron commented
Sorry for the slow response here and thanks @onbjerg for pushing the fix.

2022-04-30 16:22 UTC, onbjerg commented
Hmm, it seems to not work. Not entirely sure where `take` is from here @mattsse

2022-04-30 16:23 UTC, onbjerg commented on cast/src/lib.rs
> +                let json = if !json["abi"].is_null() { json.take("abi") } else { json };
It seems it was meant to be like this, my bad :sweat_smile: 

```suggestion
                let json = if !json["abi"].is_null() { json["abi"].take() } else { json };
```

2022-04-30 16:31 UTC, merged