forge(fix): refactor pending transactions from `script`
foundry-rs/foundry pull request #1790
Opened 2022-05-31 13:27 UTC by joshieDo

## Motivation
It didn't make much sense on how it was before. 
On top of that, there was an issue where `--resume` was starting off on a transaction which had been published already, because we didn't wait for all pending transactions.

## Solution

2022-05-31 13:47 UTC, mattsse requested changes
can't say I can follow completely at this point but have some nits :)

2022-05-31 13:47 UTC, mattsse commented on cli/src/cmd/forge/script/receipts.rs
> +        BroadcastError::Simple(format!("Failed to get pending transaction {tx_hash}"));
you can probably turn this into a closure that creates the error and get rid of the clones

2022-05-31 13:47 UTC, mattsse commented on cli/src/cmd/forge/script/broadcast.rs
> +            for payload in sequence {
```suggestion
            for (tx, signer) in sequence {
```

2022-05-31 14:52 UTC, mattsse approved these changes

2022-05-31 14:53 UTC, mattsse commented
good t merge @joshieDo ?

2022-06-01 00:00 UTC, gakonst approved these changes
makes sense - wdyt about separately adding a bit of documentation in the module showing end to end all the functionality / potential states a transaction can be and how it interplays with --resume etc.?

2022-06-01 00:01 UTC, merged