Adds contract verification via sourcify
foundry-rs/foundry pull request #1872
Opened 2022-06-08 03:05 UTC by robertabbott

## Motivation
https://github.com/foundry-rs/foundry/issues/1822

## Solution
Adds an additional option `--verification-provider` that allows the user to specify and contract-verifier other than etherscan. Omitting the option causes verify to default to etherscan. If `--verification-provider sourcify` is passed to `forge create` the contract is verified by sending hitting the[ sourcify api](https://docs.sourcify.dev/docs/api/server/check-by-addresses/)

2022-06-08 10:28 UTC, mattsse requested changes
nice!

only a few of smol nits,

a basic integration test would be nice, we have some etherscan verify integration tests here:
https://github.com/foundry-rs/foundry/blob/master/cli/tests/it/verify.rs

the `forgetest!` macro creates a new test and verify tests are currently run if the necessary env vars are set

2022-06-08 10:28 UTC, mattsse commented on cli/src/cmd/forge/verify.rs
> +            hex::encode(self.address.as_bytes()),
this formats with 0x prefix, note debug formatting is necessary here
```suggestion
            format!("{:?}", self.address),
```

2022-06-08 10:28 UTC, mattsse commented on cli/src/cmd/forge/verify.rs
> +                hex::encode(self.address.as_bytes()),
same

2022-06-08 10:28 UTC, mattsse commented on cli/src/cmd/forge/verify.rs
> +        let parsed_response = response.json::<serde_json::Value>().await?;
can we add proper bindings for this?
https://app.quicktype.io/ generates rust types for json

2022-06-08 10:28 UTC, mattsse commented on cli/src/cmd/forge/verify.rs
> +
let's move these below the `VerifyArgs`, so each cmd file starts with the actual command

2022-06-09 23:15 UTC, robertabbott commented
re: https://github.com/foundry-rs/foundry/pull/1872#discussion_r892217725

there is one result / array entry per address in the request, so there will only ever be a single item

2022-06-10 10:32 UTC, mattsse approved these changes
lgtm

2022-06-10 10:32 UTC, mattsse commented on cli/tests/it/verify.rs
> +        for verifier in VERIFICATION_PROVIDERS {
nice!

2022-06-13 09:39 UTC, onbjerg approved these changes
Two small nits otherwise LGTM

2022-06-13 09:39 UTC, onbjerg commented on cli/src/cmd/forge/verify.rs
> +        help = "Contract verification provider to use `sourcify` or `etherscan` [Default: etherscan]",
Same as above

```suggestion
        help = "Contract verification provider to use `sourcify` or `etherscan`",
```

2022-07-12 04:57 UTC, iainnash commented
Would it be possible to have an option to verify with multiple providers? or would the idea be to run the command twice in that case?

2022-07-15 12:24 UTC, kuzdogan commented on cli/src/cmd/forge/verify.rs
> +            "https://sourcify.dev/server/check-by-addresses?addresses={}&chainIds={}",
Not sure if I get it right but this is hitting the "Lookup" endpoint not the verification. `check-by-addresses` looks if the contract is already verified on Sourcify. For verification check out [`/verify`](https://docs.sourcify.dev/docs/api/server/v1/verify/)

2022-07-15 12:24 UTC, kuzdogan commented
👀 Following 👀 

Let me know if I can help

2022-07-19 09:15 UTC, tynes commented
Definitely interested in building on this PR as an upcoming Optimism testnet will be using blockscout as a block explorer and they have a contract verification API, it would be nice to also be able to support that. See https://github.com/EricxStone/hardhat-blockscout-verify

2022-08-11 03:29 UTC, tynes commented
Just wondering the status on this PR, would be great to have this merged :)

2022-08-11 06:13 UTC, gakonst commented
currently just checks for the status of the verification, but doesn't submit it! need someone to take it over the line

2022-08-11 11:16 UTC, kuzdogan commented
Not Foundry but Optimism Goerli support is added to Sourcify so you can now verify contracts through the API and other tooling we have https://github.com/ethereum/sourcify/pull/773/files @tynes

2022-08-12 09:33 UTC, rkrasiuk commented
@gakonst fyi taking over

2022-08-12 10:10 UTC, rkrasiuk commented
@tynes current etherscan verifier is fully compatible with blockscout. see comments to https://github.com/gakonst/ethers-rs/pull/1343

2022-08-12 17:05 UTC, rkrasiuk commented
closing in favor of #2748

2022-08-12 17:05 UTC, closed without merging