pin dependency to a branch
foundry-rs/foundry pull request #2241
Opened 2022-07-08 07:05 UTC by dsam82

## Motivation

Resolves #2211

## Solution

Utilises `git submodules set-branch` feature to pin a submodule to a branch. 

Adds a `-b` option to `forge install` to specify the branch, otherwise looks for tag or commit hash.

Would love to know if there is any other better solution possible.

## Example

```bash
lforge install -b rari-capital/fuse-v1@feat/
Installing fuse-v1 in "/Users/sambhavdusad/Projects/testt/lib/fuse-v1" (url: Some("https://github.com/rari-capital/fuse-v1"), tag: Some("feat/"))
There are multiple matching branches:
[0] feat/ (original branch)
[1] feat/contract-packages
[2] feat/add-vulnerability-analysis
[3] feat/add-liquidation-tests
[4] feat/add-deployment-test-flow
Please select a tag (0-4, default: 1): 1
[1] feat/contract-packages selected
    Installed fuse-v1
```

Installs fuse-v1 and pin it to branch chosen by user.

### Disclaimer

This is my first PR in Rust, so there might have been absolute horrible things that I might've done. Looking forward for your reviews :P

2022-07-08 13:26 UTC, onbjerg commented
The @ syntax we already have supports branches, so I think the primary issue in #2211 is not that you can't install a specific branch, it's that `forge update` ignores it. Any thoughts on how we might solve that instead? Imo (given @ supports branches already) a `-b` flag does not make sense

2022-07-08 13:56 UTC, dsam82 commented
`-b` flag sets the submodule to point to a particular branch using [git submodule set-branch](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-set-branch-b--branchltbranchgt--ltpathgt) option.

Updates the `.gitmodules`

```bash
[submodule "lib/fuse-v1"]
        path = lib/fuse-v1
        url = https://github.com/rari-capital/fuse-v1
        branch = feat/contract-packages
```

Now, `forge update` won't update to remote **HEAD** but to that specific **branch**

I added `-b` so that we can know that user wants to pin a branch, if he wants specific tag or commit also without forge updating it, then I think `--no-git` is the best way.

Do you have any other solution in mind?

2022-07-08 17:56 UTC, onbjerg commented
I would rather we autodetect if it is a branch then instead of adding a new flag, should be doable. How would you update to a new branch if the branch is pinned also?

2022-07-08 18:25 UTC, dsam82 commented
> I would rather we autodetect if it is a branch then instead of adding a new flag, should be doable.

So, we should first detect for branch and then for tags?

> How would you update to a new branch if the branch is pinned also?

Currently, no other way through forge, you can directly use submodules command.

```
git submodules add-branch -b <branch> <path/alias>
```

2022-07-10 19:49 UTC, onbjerg commented
@dsam82 I think we need to address moving to a different branch/tag as well in this PR otherwise the behavior might be a bit confusing

>So, we should first detect for branch and then for tags? I thought there may be some branch or tags with same name and detecting automatically might create confusions, so created a flag.

I think that's preferable, right now if a branch and a tag are named the same thing the behavior is also somewhat undefined. I also *think* (but am not entirely sure) that if a branch and a tag is named the same thing, we can expect the tag to point to the latest commit on the branch with the same name eventually, so it should be OK

2022-07-11 16:25 UTC, dsam82 commented
@onbjerg removed `-b` flag, and we can change branch after pinning through `forge install`.

```bash
forge install foundry-rs/forge-std@docs-fix
```

Changes branch to `docs-fix` even if it's pinned to another branch and updates `branch` tag in `.gitmodules`, then running `forge update` updates to that branch.

2022-07-11 16:56 UTC, mattsse requested changes
couple smol nits

also needs nightly formatting `cargo +nightly fmt`

defer to @onbjerg for final approval

2022-07-11 16:56 UTC, mattsse commented on cli/src/cmd/forge/install.rs
> +        };
use `if let Some()` syntax for Options

2022-07-11 16:56 UTC, mattsse commented on cli/src/cmd/forge/install.rs
> +        .map(|x| x.to_string())
```suggestion
        .map(str::to_string)
```

2022-07-14 06:58 UTC, onbjerg approved these changes
LGTM

2022-07-14 06:58 UTC, merged