Feat: parseJson
foundry-rs/foundry pull request #2293
Opened 2022-07-13 09:08 UTC by odyslam

## Motivation

I am opening a draft PR to gather feedback and improve code quality.

- fixes #2153 
- related to https://github.com/foundry-rs/forge-std/pull/138

## Checklist

- [x] Poc
- [x] Support arbitrarily nested JSON objects
- [x] Add Solidity tests
- [x] Improve error handling & code quality
- [x] Rebase master
- [ ] Merge forge-std library
- [ ] Merge docs

2022-07-13 11:32 UTC, mattsse requested changes
I think that should work

> If I understand correctly the ABI spec, structs are encoded as tuples.

exactly

for objects we should be able to convert them into `Vec<ParamType>` which will encode/decode as tuples, which would mean `value_to_type` is recursive over `Value::Object`

2022-07-13 11:32 UTC, mattsse commented on evm/src/executor/inspector/cheatcodes/ext.rs
> +        }
here we probably need an untagged enum and try to deserialize it in the correct hex type like this

https://github.com/foundry-rs/foundry/blob/1bfb63906c2a96112cc9292d43c95e4c4a6169ab/common/src/fmt.rs#L252-L260

2022-07-13 11:32 UTC, mattsse commented on evm/src/executor/inspector/cheatcodes/ext.rs
> +    let values: Value = jsonpath_rust::JsonPathFinder::from_str(json, key)?.find();
what's the benefit if `JsonPathFinder` here?

2022-07-13 20:27 UTC, mattsse commented
> @mattsse What do you think of the fact that json objects are not ordered, thus it's possible that the same JSON will be serialized differently with every read of the file?

iirc serde_json::Value::Object is a sorted BTreeMap.

I think we want sorted keys, and hence sorted encoded tuples so order is consistent?

2022-07-14 08:26 UTC, odyslam commented on testdata/cheats/ParseJson.t.sol
> +    }
> parseJson variant which does not take a second argument and reads the entire thing

Reads it into what? We have the JSON in stringified via the `readFile`. So what we could do is basically a library that reads the JSON via `readFile`, stores the string locally, and then does `parseJson(key)` on the stored inner value.

Agreed on the library for forge-std.

2022-07-14 08:28 UTC, odyslam commented
> > @mattsse What do you think of the fact that json objects are not ordered, thus it's possible that the same JSON will be serialized differently with every read of the file?
> 
> iirc serde_json::Value::Object is a sorted BTreeMap.
> 
> I think we want sorted keys, and hence sorted encoded tuples so order is consistent?

Yup, that sounds reasonable. Just underlining it cause that affects the order the user would have to define the attributes in the struct. While they would intuitively do it via some taxonomical or tight-packing order, they would need to know they they have to list the attributes in alphabetical order in order for the tuple to be translated into the struct correctly

2022-07-14 12:12 UTC, mattsse commented
> they would need to know they they have to list the attributes in alphabetical 

I think this is reasonable, otherwise it will cause problems if you want to parse e.g. a "transaction" json and different nodes may return a different order in the RPC response

2022-07-26 08:24 UTC, odyslam commented
@mattsse finally made it work with arbitrarily nested objects. Switched to handling them via Tokens and it became much simpler. I would like your suggestion on:
- Better error handling, especially inside the closure to reduce `unwrap()`
- parseAddress: I tried your suggestion, but didn't make it work. I think serde follows the same logic under the hood, trying different types in-order unless one decodes successfully.
- Solidity tests pass. To run them easily, you can use this one-liner: `./target/debug/forge test --root testdata --contracts cheats -vvv --match-contract ParseJson`

2022-07-30 23:27 UTC, gakonst reviewed
there's a commented out test + needs a test for writeJSON, not sure i exactly get how it's supposed to be used! 

the parseJSON flow looks good

2022-07-30 23:27 UTC, gakonst commented on evm/src/executor/inspector/cheatcodes/ext.rs
> +        .unwrap()
replace with `?` and `.ok_or` to convert the Option into a Result

2022-07-31 09:46 UTC, odyslam commented
@gakonst I added a new comment on the [issue](https://github.com/foundry-rs/foundry/issues/2153#issuecomment-1200389140) on a proposed API for writeJson. I haven't found something that I love, so I want to get some alignment before I get full steam ahead implementing. 

The one I have implemented right now, is only good for writing simple values (not arrays, not struct) at the first "level" of a json (so not being able to write in a nested object). I proposed a new API, but it's meh. Any idea is more than welcome.

2022-07-31 11:13 UTC, mattsse requested changes
couple nits, otherwise ,lg

2022-07-31 11:13 UTC, mattsse commented on evm/src/executor/inspector/cheatcodes/ext.rs
> +        Err(Token::String("Could not decode field".to_owned()))
```suggestion
        Err(Token::String("Could not decode field".to_string()))
```

2022-07-31 11:13 UTC, mattsse commented on evm/src/executor/inspector/cheatcodes/ext.rs
> +            value_to_token(val).unwrap()
lets not unwrap here instead collect over `::Result<Vec<_>,_>`

2022-07-31 11:13 UTC, mattsse commented on evm/src/executor/inspector/cheatcodes/ext.rs
> +    overwrite: &bool,
don't borrow Copy types
```suggestion
    overwrite: bool,
```

2022-08-01 07:53 UTC, OliverNChalk commented
Hey, just testing this out locally and haven't had any issues parsing JSON files yet. I merged master in and it was fine, just one compile issue fixed here: https://github.com/proximacapital/foundry/commit/e6867e11c89e21a1dc614d2cc68dd292ec2e3537

Was wondering if there was an eta? I'll continue building out my json usage locally but struggling to see a practical (i.e. not compiling from source) way to get access to this feature in CI before it merges?

2022-08-01 17:24 UTC, gakonst commented
`foundryup -P 2293` will get this working for you I think?

2022-08-01 23:41 UTC, OliverNChalk commented
Build currently failing but ill def use that flag in the future, for now running off of a fork

2022-08-10 17:31 UTC, mattsse approved these changes
a general usage is limited due to some assumptions and limitations regarding encoding, but it is definitely useful and we should add that

needs rebase though

2022-08-10 20:29 UTC, mds1 commented
> a general usage is limited due to some assumptions and limitations regarding encoding, but it is definitely useful and we should add that

What limitations are these? 

Also @odyslam should this be taken out of draft now?

2022-08-10 21:14 UTC, odyslam commented
Tomorrow will do the following:
- remote writeJson code (will be replaced eitherway)
- rebase
- put out of draft and ping for review. Goal to merge tomorrow

Then, I will create a new branch to start working on @mattsse suggestion for `writeJson`. 

Sorry for delaying the feature for so long.

2022-08-11 00:09 UTC, gakonst commented
SGTM. Let's get this over the line and iterate on the `writeJSON` separately.

2022-08-11 13:00 UTC, mattsse commented
> > a general usage is limited due to some assumptions and limitations regarding encoding, but it is definitely useful and we should add that
> 
> What limitations are these?

for structs, we currently have no way of knowing how the target struct looks like so current assumption is that the sol type matches the json object 1:1, right @odyslam?

2022-08-11 13:06 UTC, odyslam commented
Not only that, but that also the attributes of the struct are defined in alphabetical order
Le 11 août 2022 à 3:00 PM +0200, Matthias Seitz ***@***.***>, a écrit :
> > > a general usage is limited due to some assumptions and limitations regarding encoding, but it is definitely useful and we should add that
> > What limitations are these?
> for structs, we currently have no way of knowing how the target struct looks like so current assumption is that the sol type matches the json object 1:1, right @odyslam?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-08-11 13:51 UTC, merged

2022-08-11 14:03 UTC, odyslam commented
@mattsse will proceed with `forge-std` and docs update shortly. 

Thanks for the JSON file test fix.

2022-08-21 16:15 UTC, 0xPhaze commented
Does this work with `bytes32` and `bytes`? I am getting some weird results there.

2022-08-21 16:32 UTC, OliverNChalk commented
@0xPhaze I am able to parse this:
![image](https://user-images.githubusercontent.com/11343499/185801291-13fbeca3-8502-4c2b-8db1-6d868d48b737.png)

Into this:
![image](https://user-images.githubusercontent.com/11343499/185801299-d7b9be56-7e4f-473f-bf12-b0cf410bfb6b.png)

2022-08-21 16:39 UTC, 0xPhaze commented
Hm.. are you able to parse something like this?
![image](https://user-images.githubusercontent.com/103113487/185801559-ac7a863a-be56-4f4b-9860-082ece5d5dd3.png)

2022-08-21 17:05 UTC, odyslam commented
Hey, 

so currently the above will be returned as a type string. I have added a fix for that and will pr now

2022-08-21 17:29 UTC, odyslam commented
@0xPhaze that should do it

https://github.com/foundry-rs/foundry/pull/2866