Change the defult Contract to Counter
foundry-rs/foundry pull request #2640
Opened 2022-08-06 01:24 UTC by Tirthnp

## Motivation

## Solution

2022-08-08 14:13 UTC, mattsse requested changes

2022-08-08 14:13 UTC, mattsse commented on cli/assets/CounterTemplate.sol
> +contract Counter {}
this should have a `counter` variable which can be incremented

2022-08-08 14:13 UTC, mattsse commented on cli/assets/CounterTemplate.t.sol
>      function testExample() public {
this should be something like `testIncrement` that calls `Counter.increment` and then uses assertEq to ensure it was successful

2022-08-08 18:24 UTC, Tirthnp commented
@mattsse would the changes makes sense ?

2022-08-08 18:26 UTC, mattsse requested changes
@onbjerg I think this is a reasonable example

I wonder if it's worth it to add some docs.
since this is considered a template I don't think it's worth it.

also maybe we want to have only 1 test because usually these are renamed/deleted anyway. so only having 1 test should be enough?

2022-08-08 18:26 UTC, mattsse commented on cli/assets/CounterTemplate.t.sol
> +        assert(counter.number() == 1);
should use assertEq here

2022-08-08 18:31 UTC, Tirthnp commented on cli/assets/CounterTemplate.t.sol
> +        assert(counter.number() == 1);
Should I just keep the testIncrement ?

2022-08-09 16:35 UTC, gakonst commented
i kinda dont wanna anchor into the Counter as an example - what's the issue with calling the default contract this name?

2022-08-09 16:39 UTC, mds1 commented
@gakonst Just curious, why not?

I think counter can be an interesting template, because it leaves room to expand it and have `forge init` include a very simple test suite that demonstrates each test type.

2022-08-09 17:10 UTC, mattsse commented
ref https://github.com/foundry-rs/foundry/issues/2451

2022-08-09 19:17 UTC, onbjerg commented
i think this is ok, simple enough to resolve #2451, not so big that it will cause a lot of churn over what to add/remove etc

no need to add docs for it although the book does need to be updated since it does reference the default template in some places

2022-08-12 13:38 UTC, Tirthnp commented
Just wanted to confirm about what changes I still need to make ? @onbjerg @mattsse

2022-08-12 21:34 UTC, gakonst approved these changes
OK no strong opinions. I liked the blank template because it doesn't require you to delete any code, but I guess nicer to have it this way.

2022-08-12 21:34 UTC, gakonst commented on cli/assets/CounterTemplate.t.sol
> +        assertEq(counter.number(),10);
```suggestion
    function testSetNumber(uint256 x) public {
        counter.setNumber(x);
        assertEq(counter.number(), x);
```

2022-08-12 21:34 UTC, gakonst commented on cli/assets/CounterTemplate.t.sol
> +        assertEq(counter.number(),1);
```suggestion
        assertEq(counter.number(), 1);
```

2022-08-12 21:35 UTC, merged