Compile Etherscan Sources for use in Debugger
foundry-rs/foundry pull request #3006
Opened 2022-08-29 14:49 UTC by OmkarB

## Motivation
Debugging with sources is helpful, pulling sources from etherscan expands amount of source code available. Built off of [this PR](https://github.com/foundry-rs/foundry/pull/1413). 

## Solution
1 . When identifying addresses for traces, collect addresses & sources.
2. Compile each contract address [and downloads the solc version required)
3. Provide them to the TUI debugger. 

Still can't handle vyper, `--via-ir`, or multifile sources.

In order to make these changes, we migrate the `compile` module to the common module, to make the dependecy pattern more obvious and remove cyclical imports

2022-08-30 17:38 UTC, gakonst commented
Can we make this also work with `forge test --debug`?

2022-09-10 18:39 UTC, gakonst commented
@OmkarB bump, i think there's a bunch of conflicts on the CLI due to a recent refactor? we can merge this at current state and do the `forge test --debug` and `forge debug` in a follow up PR maybe?

2022-09-12 02:37 UTC, OmkarB commented
sorry for the delay @gakonst -- works for me. I'll resolve conflicts in this one and follow up with a separate PR to include updates to `forge test --debug` and  `forge debug`.

2022-09-15 13:32 UTC, OmkarB commented
@gakonst wyt? Fixed conflicts and cleaned up code a bit. Should we merge into master?

2022-09-16 00:19 UTC, gakonst requested changes
I am working on parallelizing the loop. I think we should do caching first as a followup, and then the other 2 we mentioned.

2022-09-16 00:29 UTC, gakonst commented
@OmkarB this generally looks good - can you take a pass at https://github.com/foundry-rs/foundry/pull/3006/commits/0e4f63977a48096d2c1e3c10ebb14e399c1a5a00 and see if it improves performance? It seems not to locally for me which surprises me. cc @mattsse this is good to merge if we like the code changes + agree on the followups

2022-09-16 21:12 UTC, OmkarB commented
@gakonst it's definitely faster locally for me. Doesn't make much of a difference for 2/3 contracts but noticed a substaintial improvement when there were more. 
If this looks good, should we merge? @mattsse or would it be better to merge the extracted code from #3235.   I can work on caching the artifacts as the immediate followup.

2022-09-16 22:27 UTC, mattsse commented
sgtm, 
let's merge #3235, rebase this and merge,

2022-09-16 23:55 UTC, OmkarB commented
@mattsse I dropped the changes to the compile module that I made in preference for what you pulled out, and combined any other changes with the second commit. Kept the debugger integration logic.

2022-09-16 23:57 UTC, gakonst approved these changes
beautiful.

2022-09-16 23:57 UTC, gakonst commented on common/src/compile.rs
> +#[allow(missing_docs)]
Why did we delete this?

2022-09-16 23:57 UTC, gakonst commented on common/src/compile.rs
> -/// How big the contract is and whether it is a dev contract where size limits can be neglected
Same Q

2022-09-17 00:13 UTC, merged

2023-04-13 13:36 UTC, AllTradesz commented
> sorry for the delay @gakonst -- works for me. I resolved the conflicts in this one and follow up with a separate PR to include updates to `forge test --debug` and `forge debug`.

hiya @omkarb, browsing this topic and am wondering if the separate PR you anticipated got done.. Would be fantastic if sources would download in these contexts too. Thx!