[WIP] all(cast): General refactor, add to_base
foundry-rs/foundry pull request #3125
Opened 2022-09-07 21:33 UTC by DaniPopes

## Motivation

Initially wanted to add a `to_base`, then saw there already was some kind of base parsing implemented for shl/shr, so I seized the opportunity to do some more stuff

## Solution

- adding `cast --to-base <number> <to_base> [<from_base>]`, which tries to match `<number>` to a base (binary, hex...) if prefixed or by other means, and convert it to `<to_base>`, with an optional `<from_base>` in case it's ambiguous, similar to how it is done currently in `SimpleCast::{shl, shr}`
- ordering SimpleCast's functions by trying to match a from/to pair: `{from,to}_fix`
- standardizing names: `--to-asci` matching `SimpleCast` function was `ascii()` while most others have the same name as the flag;
- standardizing fn args: `from_wei`, `to_wei`, `to_unit` all had different args while essentially doing and matching the same thing;
- refactoring some weird hex formatting (`to_`)

Any suggestion is welcome!

2022-09-08 04:20 UTC, DaniPopes commented
Failing lint unrelated

2022-09-09 12:41 UTC, mattsse requested changes
this is great!
tysm!

only have a few nits, overall lgtm

2022-09-09 12:41 UTC, mattsse commented on cast/src/lib.rs
> +    pub fn from_fix(decimals: u32, value: &str) -> Result<U256> {
```suggestion
    pub fn from_fixed_point(decimals: u32, value: &str) -> Result<U256> {
```

2022-09-09 12:41 UTC, mattsse commented on cast/src/lib.rs
> +        Ok(utils::to_checksum(address, None))
looks like we don't need a result here?

2022-09-09 12:41 UTC, mattsse commented on cast/src/lib.rs
> +            _ => eyre::bail!("invalid unit"),
let's include the invalid values in the error

2022-09-09 12:41 UTC, mattsse commented on cast/src/lib.rs
> +        .to_string())
for readability use two steps here

let wei = match ...
Ok(wei.to_string())

2022-09-09 12:41 UTC, mattsse commented on cast/src/lib.rs
> +                let mut json: serde_json::Value = serde_json::from_str(&file)?;
this needs to be rebased after https://github.com/foundry-rs/foundry/pull/3124

2022-09-09 12:41 UTC, mattsse commented on cli/src/opts/cast.rs
> +        unit: String,
good change!

2022-09-09 19:13 UTC, mattsse commented
thanks!

the failing test is bcause checksum address no longer returns an result, just need to remove the unwrap

2022-09-09 19:13 UTC, mattsse commented
> I believe failing tests are unrelated
> 
> what do we think of deprecating `--to-dec N` and `--to-hex N` in favor of `--to-base N dec/hex`? or should we just keep them as aliases and hint to `--to-base` in the help like in `--{to,from}wei`?

let's just keep them as clap `visible_alias`

2022-09-09 22:22 UTC, DaniPopes commented
> the failing test is because checksum address no longer returns an result, just need to remove the unwrap
oops missed that one, thanks

> let's just keep them as clap `visible_alias`
alright

2022-09-10 00:05 UTC, gakonst reviewed
Thanks for this! Hate to be this guy but can we split the PR in separate ones that each do a specific thing? The rename/refactor of a bunch of things makes somethings a bit hard to parse I think? I love the changes but ideally we can get them in separately.

2022-09-10 00:23 UTC, mattsse commented
I guess it would make sense to submit at least the changes/additions to `base.rs` and all the Cast improvements/updates separately.

2022-09-10 02:45 UTC, DaniPopes commented
makes sense, closing this then

2022-09-10 02:45 UTC, closed without merging