Optimize nonce calculations
foundry-rs/foundry pull request #3859
Opened 2022-12-08 15:24 UTC by kubmichael

## Motivation
During eth_sendTransaction anvil is doing evm_mine operation with out writing it to storage in order to calculate nonce
This is look likes very expensive (also see this during profiling), especially when sending many transactions

## Solution
Simplify nonce calculation, but looking for max nonce value

2022-12-08 17:14 UTC, mattsse commented
> During eth_sendTransaction anvil is doing evm_mine operation with out writing it to storage

sorry, but can you please be a bit more specific here?

2022-12-08 17:21 UTC, mattsse requested changes
ah ok, I get it now.

lgtm, but I'd like to see some additional docs here.

2022-12-09 06:39 UTC, gakonst requested changes
Agreed would love this functionality to be part of a function that's unit tested - good addition otherwise, thank you for the contribution.

2022-12-11 08:39 UTC, kubmichael commented on anvil/src/eth/backend/mem/mod.rs
> +        if let Some(BlockRequest::Pending(pool_transactions)) = block_request.as_ref() {
Looks like in similar way - [hardhat](https://github.com/NomicFoundation/hardhat/blob/dbf7c0b33001ebca01ac3737e8599ef251cf0de7/packages/hardhat-core/src/internal/hardhat-network/provider/TxPool.ts#L248)
```
    const pendingTxs = this._getPendingForAddress(accountAddress.toString());
    const lastPendingTx = pendingTxs?.last(undefined);

    if (lastPendingTx === undefined) {
      return this._getNextConfirmedNonce(accountAddress);
    }

    const lastPendingTxNonce =
      this._deserializeTransaction(lastPendingTx).data.nonce;
    return lastPendingTxNonce + 1n;
```

2022-12-11 08:46 UTC, kubmichael commented on anvil/src/eth/backend/mem/mod.rs
> +                    if nonce.ge(&res) {
Maybe it isn't best code, I am trying to find any match, because first value is 0, so I am doing ge, I think I will improve it

2022-12-11 10:31 UTC, kubmichael commented
> Agreed would love this functionality to be part of a function that's unit tested - good addition otherwise, thank you for the contribution.

May addition is tested as part of getTransactionCount, but I can add additional unit tests, can you point me where is the best place to put it?

2022-12-12 16:22 UTC, mattsse approved these changes
lgtm

2022-12-13 11:14 UTC, mattsse approved these changes

2022-12-13 12:51 UTC, merged