bump ethers-rs dependencies to onbjerg's ast
foundry-rs/foundry pull request #3899
Opened 2022-12-16 17:44 UTC by iFrostizz

## Motivation

Following the discussion https://github.com/gakonst/ethers-rs/pull/1943 about checking for issues related to foundry dependency to ethers-rs ast that has been reworked by @onbjerg 
Issues seems to occur on the coverage part as expected. I am happy to refactor this once the ast is merged on the ethers-rs side.

2022-12-18 11:06 UTC, gakonst commented
Nice! OK would prefer that we do the fixes on this PR against the ethers-rs branch and merge them both in lockstep, instead of merging one, then doing this PR, as it can cause breakages

2022-12-18 22:06 UTC, iFrostizz commented
> Nice! OK would prefer that we do the fixes on this PR against the ethers-rs branch and merge them both in lockstep, instead of merging one, then doing this PR, as it can cause breakages

Can we make an ether-rs branch so I can change the PR target from my branch with the ast, update it on the foundry repo in this PR, and then do another PR as a 2nd step after merging the PR from ethers into master ?

2022-12-19 00:24 UTC, gakonst commented
ye that works

2022-12-19 10:44 UTC, iFrostizz commented
how does that look @gakonst ?

2022-12-21 21:58 UTC, iFrostizz commented
Bump

2022-12-22 12:44 UTC, mattsse commented
looks like it, so supportive of merging both

2022-12-22 13:23 UTC, gakonst commented
@iFrostizz merged - let's make this use ethers master and good to go

2022-12-22 14:52 UTC, mattsse commented
okay, there are way more breaking changes here than anticipated...

this PR didn't actually check against the ethers PR `rev = bb4af1c` is not the right check so this was misleading

2022-12-22 16:22 UTC, gakonst commented
Merged the reverted PR. @iFrostizz this is why we should not try to rush things 😅

2022-12-22 17:10 UTC, DaniPopes requested changes
Didn't realize you were bumping ethers here so I closed #3937

2022-12-22 17:10 UTC, DaniPopes commented on config/src/chain.rs
> +    type Error = String;
https://github.com/foundry-rs/foundry/pull/3937/commits/322ba09a4cee500e77c49ef488ecb7037c909b53

```suggestion
    type Error = <ethers_core::types::Chain as TryFrom<u64>>::Error;
```

2022-12-22 17:10 UTC, DaniPopes commented on config/src/chain.rs
> +            Chain::Id(id) => ethers_core::types::Chain::try_from(id).map_err(|err| err.to_string()),
https://github.com/foundry-rs/foundry/pull/3937/commits/322ba09a4cee500e77c49ef488ecb7037c909b53

```suggestion
            Chain::Id(id) => id.try_into(),
```

2022-12-23 13:42 UTC, merged

2022-12-28 23:30 UTC, iFrostizz commented
Sorry friends but what exactly caused this issue ?
"rev = bb4af1c was not the right check so the ci results of this PR were misleading"
My main intent was to pin the dependencies of foundry to ethers as the "latest stable", then merge the ast in ethers-rs to give a little bit of time in case anything was broken on foundry side (which seems to have happened), and after fixing open a new PR in order to update foundry as well as the dependencies.