ci: replace with sepolia
foundry-rs/foundry pull request #4004
Opened 2023-01-01 10:25 UTC by sambacha

all heil sepolia

2023-01-01 10:53 UTC, mattsse requested changes
wdyt @joshieDo

2023-01-01 10:53 UTC, mattsse commented on .github/workflows/live-test.yml
> +            GOERLI_RPC_URL: https://sepolia.infura.io/v3/fe24c1ff7cfb4ddabec77f512e60c5b6
should also rename this var

2023-01-01 11:00 UTC, sambacha commented on .github/workflows/live-test.yml
> +            GOERLI_RPC_URL: https://sepolia.infura.io/v3/fe24c1ff7cfb4ddabec77f512e60c5b6
yea I wanted to see if it works 1st

2023-01-03 14:31 UTC, gakonst commented on .github/workflows/live-test.yml
> +  CARGO_INCREMENTAL: 0
pls remove unrelated stuff

2023-01-03 14:31 UTC, gakonst commented on .github/workflows/live-test.yml
> +  pull_request:
pls remove unrelated changes

2023-01-06 11:55 UTC, sambacha commented
@mattsse can we add dispatch? this wont build unless is a push onto master so not exactly ideal

2023-01-17 19:14 UTC, gakonst commented
would like to keep thing as they are, thanks!

2023-01-17 19:14 UTC, closed without merging

2023-01-17 19:16 UTC, sambacha commented
> would like to keep thing as they are, thanks!

Close the corresponding issue then while your at it 😉