feat(cast): add mnemonic key generation to wallet new
foundry-rs/foundry pull request #4128
Opened 2023-01-19 17:56 UTC by mitche50

## Motivation

Generating new wallets only allows for a user to generate a private key and associated address.  Many wallets default import mnemonic seeds, so we should have an option to generate a mnemonic along with the wallet.

## Solution

I've added an `--mnemonic` flag to the `cast wallet new` command which when provided will generate and provide the mnemonic seed.  This uses the `tiny-bip39` (https://docs.rs/crate/tiny-bip39/latest) crate to generate a random 12 word mnemonic and feeds into the ethers `MnemonicBuilder`.

2023-01-19 18:46 UTC, roynalnaruto commented
`ethers-signers` offers a mnemonic wallet, which provides a nice interface to work with and a `mnemonic_to_wallet` fallible method to convert to a `Wallet<SigningKey>>` type. My suggestion is that using this would simplify your changes and make it easier to maintain :)

2023-01-19 19:22 UTC, mitche50 commented
> `ethers-signers` offers a [mnemonic wallet](https://github.com/gakonst/ethers-rs/blob/master/ethers-signers/src/wallet/mnemonic.rs), which provides a nice interface to work with and a `mnemonic_to_wallet` fallible method to convert to a `Wallet<SigningKey>>` type. My suggestion is that using this would simplify your changes and make it easier to maintain :)

The problem with the `ethers-signers` library is it doesn't surface the mnemonic phrase used to generate the wallet in `build_random` and requires a phrase to be set in `build`.  The point of this PR was to provide the mnemonic in the return to the user so they can use this to store their seed vs. the hex private key only.

2023-01-19 20:18 UTC, DaniPopes requested changes

2023-01-19 20:18 UTC, DaniPopes commented on cli/src/cmd/cast/wallet/mod.rs
> +                            std::process::exit(1);
Please avoid using process::exit, return instead with `eyre::bail!("msg")` or `return Err(eyre::eyre!("msg"))`

2023-01-19 20:18 UTC, DaniPopes commented on cli/src/cmd/cast/wallet/mod.rs
> +                    if !word_counts.contains(&word_count) {
I don't think this is necessary to check ourselves as Mnemonic will just throw an error

2023-01-20 17:17 UTC, DaniPopes approved these changes

2023-01-22 21:10 UTC, gakonst commented
> The problem with the ethers-signers library is it doesn't surface the mnemonic phrase used to generate the wallet in build_random and requires a phrase to be set in build. The point of this PR was to provide the mnemonic in the return to the user so they can use this to store their seed vs. the hex private key only.

Would you be open to providing a PR to ethers-signers which adds these features?

Thanks for taking this on!

2023-02-03 21:39 UTC, to4kag approved these changes

2023-03-13 13:22 UTC, shidaxi commented
Hey @mitche50 how is this feature going, could you merge to master?

2023-03-13 13:32 UTC, mitche50 commented
> Hey @mitche50 how is this feature going, could you merge to master?

The feature is functional when testing locally, but not sure if the team wants to merge this to master.  @gakonst requested this be a PR to ethers-signers vs. to foundry but I haven't had time to move it over.

2023-03-14 02:56 UTC, gakonst commented
There's some WIP https://github.com/gakonst/ethers-rs/pull/2238 with comments from Matt in there!

2023-06-22 22:20 UTC, Evalir commented
Closing as stale.

2023-06-22 22:20 UTC, closed without merging