fix: recognize invariant tests as tests
foundry-rs/foundry pull request #4461
Opened 2023-03-01 20:03 UTC by mds1

## Motivation

When running `forge build --sizes` to verify contracts are below the size limit, test contracts are filtered out. This happens here: https://github.com/mds1/foundry/blob/65f081ada3ba53b62a05dcc9623ca92498d6af5c/common/src/compile.rs#L150-L161

The problem is that contracts that only have invariant tests are not counted, because those tests start with `invariant` instead of `test`, and get flagged as being over the size limit.

## Solution

Update the `is_test` method to count invariant tests as tests also. I'm not certain if that method ever is used somewhere where the test must not be an invariant test. If so, we may need to update this solution. But from my look as `is_test()` usage, this seems ok, though there are instances where `.is_test()` is used to collect all tests, so now additional tests will be included there

2023-03-01 20:21 UTC, mds1 commented
Potential side effects:
- Counting invariant tests toward code coverage? From [here](https://github.com/foundry-rs/foundry/blob/94777647f6ea5d34572a1b15c9b57e35b8c77b41/evm/src/coverage/analysis.rs#L530). Would close https://github.com/foundry-rs/foundry/issues/4007 is that's correct
- Invariant tests might be included in gas reports, and now properly excluded, from [here](https://github.com/foundry-rs/foundry/blob/94777647f6ea5d34572a1b15c9b57e35b8c77b41/forge/src/gas_report.rs#L82)
- Invariant tests may not have been targetable before by match test? From [here](https://github.com/foundry-rs/foundry/blob/94777647f6ea5d34572a1b15c9b57e35b8c77b41/cli/src/cmd/forge/test/mod.rs#L493)
- `forge test` might now run invariants twice, per [this](https://github.com/foundry-rs/foundry/blob/94777647f6ea5d34572a1b15c9b57e35b8c77b41/forge/src/runner.rs#L273), so maybe we need to change this line to something like `is_regular_test` to exclude invariants?

2023-03-02 12:06 UTC, mattsse requested changes
hmm, I'm hesitant to touch these filter functions directly and mix test/invariant test.
can we instead add a `|| .is_invariant_test` to where this is checked

this should be it:

https://github.com/foundry-rs/foundry/blob/main/common/src/compile.rs#L157-L157

2023-03-02 12:06 UTC, mattsse commented on common/src/traits.rs
> +        self.starts_with("test") || self.is_invariant_test()
this could lead to some side effects because the test runner differentiates between test and invariant test.

2023-03-02 14:42 UTC, mattsse commented
sorry, github plugin misconfigured

intended to ref this

https://github.com/foundry-rs/foundry/blob/94777647f6ea5d34572a1b15c9b57e35b8c77b41/common/src/compile.rs#L157

2023-03-08 14:16 UTC, mds1 commented
Closing this, will open a new PR with the right fix which I think will be in ethers-solc where the solc warnings are suppressed

2023-03-08 14:16 UTC, closed without merging