dep(solang-parser): update to 0.2.3
foundry-rs/foundry pull request #4477
Opened 2023-03-05 11:16 UTC by rkrasiuk

Update `solang-parser` to `0.2.3` with support for solidity `0.8.19`.
Blocked by https://github.com/gakonst/ethers-rs/pull/2229

2023-03-05 12:21 UTC, mattsse approved these changes
lgtm,

this supersedes #4458?

2023-03-05 12:23 UTC, rkrasiuk commented
@mattsse that's right. also, blocked by https://github.com/gakonst/ethers-rs/pull/2219

2023-03-06 06:46 UTC, DaniPopes requested changes

2023-03-06 06:46 UTC, DaniPopes commented on evm/src/fuzz/strategies/int.rs
> +            1 => -offset - <i32 as Into<I256>>::into(1),
#4463

2023-03-06 10:37 UTC, merged