feat(evm): add "expectEmit" variants
foundry-rs/foundry pull request #4479
Opened 2023-03-05 20:39 UTC by PaulRBerg

## Motivation

From the Foundry Book on [best practices](https://book.getfoundry.sh/tutorials/best-practices):

> When testing events, prefer setting all `expectEmit` arguments to `true`, i.e. `vm.expectEmit(true, true, true, true)`.

This PR introduces two `expectEmit` cheatcode variants that have no boolean arguments. All of the topics (`checkTopic1`, `checkTopic2`, `checkTopic3`, and `checkData`) are set to `true` by default.

## Solution

I added the variants in the ABIGEN defined in `evm/src/executor/abi/mod.rs`, and then I implemented them in Rust in `evm/src/executor/inspector/cheatcodes/expect.rs`.

I'm not sure if any tests need to be written for this?

2023-03-07 10:32 UTC, mattsse requested changes
this seems like a reasonable addition.

wdyt @mds1 

would appreciate some additional tests for expectEmit:

https://github.com/foundry-rs/foundry/blob/28b2ae6d5ad3e802b813b679e26bc15b9b8d230b/testdata/cheats/ExpectEmit.t.sol#L54-L54

2023-03-07 15:46 UTC, mds1 commented
@mattsse supportive of this, it's been discussed a few times and just never PR'd in

LGTM, thanks @PaulRBerg!

2023-03-08 10:11 UTC, PaulRBerg commented
It looks like there is a failing test, but it is unrelated to this PR?

> [FAIL. Reason: Could not instantiate forked environment with fork url: https://rpc.ankr.com/bsc_testnet_chapel] testRpcs()

2023-03-08 10:23 UTC, mattsse commented
yep,
unrelated!

2023-03-08 10:23 UTC, merged