feat(evm): support multiple languages for deriveKey cheatcode
foundry-rs/foundry pull request #4688
Opened 2023-04-02 15:38 UTC by 0xYYY

## Motivation

Resolves #4560.

## Solution

Add support for other languages' wordlist in https://github.com/summa-tx/bitcoins-rs/pull/119/.

2023-04-02 16:28 UTC, mattsse requested changes
nice!

nit re str matching

2023-04-02 16:28 UTC, mattsse commented on evm/src/executor/inspector/cheatcodes/util.rs
> +        HEVMCalls::DeriveKey2(inner) => match inner.2.as_str() {
I'd like to have this as standalone function `derive_key_with_wordlist` that accepts the wordlist as str. perhaps even worth having an enum for this

2023-04-04 15:56 UTC, prestwich commented
`coins-bip39@0.8.4` contains non-english wordlists. Thanks @0xYYY!

2023-04-10 20:01 UTC, 0xYYY commented
pending another fix https://github.com/summa-tx/coins/pull/120

2023-04-10 20:08 UTC, DaniPopes commented on Cargo.toml
> +ethers-solc = { git = "https://github.com/0xYYY/ethers-rs", branch = "chore/bump-bitcoin-rs" }
We don't depend on ethers git anymore, can this be in a new release?

2023-05-05 05:38 UTC, Evalir commented
hey @0xYYY — do you plan on getting back to this soon?

2023-05-06 09:50 UTC, 0xYYY commented
> hey @0xYYY — do you plan on getting back to this soon?

yeah, plan to finish this around next week

2023-05-08 16:29 UTC, 0xYYY commented
added a standalone `derive_key_with_wordlist ` function, bumped ethers version, rebased on master, all tests have passed, ready for review

cc @Evalir @mattsse

2023-05-08 16:41 UTC, Evalir approved these changes
this lgtm—deferring to matt for final approval. we could maybe add a simple failing test to ensure it fails as expected?

2023-05-10 15:02 UTC, 0xYYY commented
> hmm seems we have some tests failing?

yeah, but weirdly can't see any details about why the tests failed

<img width="1436" alt="Screenshot 2023-05-10 at 23 01 38" src="https://github.com/foundry-rs/foundry/assets/86655648/80b265e8-509d-42a0-b759-056b985ee007">

2023-05-10 15:24 UTC, 0xYYY commented
> hmm seems we have some tests failing?

seems like the failing tests have ben re-ran and all tests have passed now

2023-05-10 15:25 UTC, Evalir commented
yup guessed they were just outage/unrelated failures, nice! will wait for matt to merge—nice work :)

2023-05-17 14:14 UTC, Evalir commented
hey @0xYYY — do you think we could rebase this? sorry for the extra work, but we recently refactored the abigen part of cheatcodes so will need to redo that bit

2023-05-19 13:58 UTC, 0xYYY commented
> hey @0xYYY — do you think we could rebase this? sorry for the extra work, but we recently refactored the abigen part of cheatcodes so will need to redo that bit

no prob, on it

2023-05-21 21:35 UTC, Evalir approved these changes
aight this seems ok now—just seems we have an unrelated ci failure due to a flaky test

2023-05-23 14:37 UTC, 0xYYY commented
>  will wait for matt to review/merge—nice work :)

hi @mattsse, pls let me know if there are any changes that i can make to push forward this pr, thx

2023-06-16 06:20 UTC, Evalir approved these changes
This is good, but will need a rebase & a redo on the abi crate prob. will do so tomorrow and get this over the line cc @mattsse

2023-06-23 14:17 UTC, merged

2023-06-24 06:52 UTC, 0xYYY commented
thanks @Evalir for pushing this over the line