Change default FOUNDRY_DIR value in installation files
foundry-rs/foundry pull request #4738
Opened 2023-04-14 12:55 UTC by joaop21

## Motivation

The installation scripts assume `$HOME` as the default directory to store foundry files. This is not wrong, but we are defiling the `$HOME` directory. 
Some users might have proper configurations so that application-specific data is stored somewhere else logically.
We should follow [XDG Base Directory](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) specification.

## Solution

Following XDG Base Directory specification, this kind of data should be in `$XDG_DATA_HOME`.
This PR updates the installation scripts to use this variable instead of `$HOME`,

2023-04-14 14:09 UTC, mattsse requested changes
did not work for me

```
./install                                                                                                                                                                                               
Installing foundryup...
mkdir: /.foundry: Read-only file system
```

2023-04-14 14:49 UTC, DaniPopes commented
I don't know if `XDG_*_*` env vars are set on all platforms like `HOME` is. Besides this should probably be `XDG_CONFIG_HOME` instead of `DATA`.

Rust's Cargo package manager uses `$HOME/.cargo` or `%USERPROFILE%\.cargo` for binaries and the package registry, which I believe is what we were going for initially

2023-04-21 10:45 UTC, joaop21 commented
@mattsse forgot to default to home

2023-04-21 10:48 UTC, joaop21 commented
@DaniPopes Yes, this should probably go to the `$XDG_CONFIG_HOME`. With a `$BASE_DIR` we can default to `$HOME` if `$XDG_CONFIG_HOME` var doesn't exist.

2023-04-22 07:20 UTC, mattsse approved these changes
lgtm

pending @DaniPopes

2023-04-22 07:20 UTC, mattsse commented on foundryup/foundryup
> +FOUNDRY_DIR=${FOUNDRY_DIR-"$BASE_DIR/.foundry"}
I don't really have strong opinions about xdg paths,
but I know this has been requested a few times.
Using the basedir as fallback is reasonable imo.

I assume if the xdg paths are set then the user knows what they're doing.

tested locally works as expected without xdg paths set

2023-05-04 17:43 UTC, mattsse commented
okay, this seems totally fine tested with no xdg setting

2023-05-04 17:43 UTC, merged

2023-05-06 01:08 UTC, sambacha commented
If we are going to follow the spec, why not also follow it for CACHE as well?

2023-05-06 01:50 UTC, sambacha commented
```bash
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/forge/<rpc cache, or solc cache, or whatever"
```