`REVM`: 3.x Migration
foundry-rs/foundry pull request #4757
Opened 2023-04-17 22:42 UTC by Evalir

## Motivation

REVM needed to be updated to the latest version (3.x) so we can start working on the big rewrites & new features.

## Solution

Migrates types/imports to conform to 3.x. These changes are focused on converting types—I'm deliberately choosing to keep the existing types that don't conflict there for now. The strategy is more or less as follows:

All of the types that need to use the revm types (e.g trait impls or structs/traits that interact very closely with revm) are switched.
Everything else is just converted when needed (see evm crate utils for utility functions)

There's also the [old](https://github.com/mattsse/foundry/pull/2) PR for historical comments.

2023-04-18 01:24 UTC, Evalir commented on anvil/src/eth/backend/executor.rs
> +                    DatabaseError::TransactionNotFound(H256::from_str("0x").unwrap()),
Note that this error is very much a placeholder—We probably need another variant to properly represent the inspector failing.

2023-04-18 01:24 UTC, Evalir commented on anvil/src/eth/backend/executor.rs
> +                (halt_to_instruction_result(reason), gas_used, None, None)
Unsure if the gas refund calculation is accurate here (and on the other places this `ExecutionResult` is matched)

2023-04-18 01:24 UTC, Evalir commented on anvil/src/eth/backend/mem/mod.rs
> +            Err(e) => return Err(BlockchainError::EvmError(InstructionResult::FatalExternalError)),
Also using this error as a placeholder—probably also need another variant for this type of inspector error

2023-04-20 11:25 UTC, mattsse requested changes
incredible work!

even if all the conversions are a bit horrible, we need to do this to support revm and they will become obsolete eventually.

could you please enable contributions by mainter? I have a few local changes that I'd like to push.
I think the issue is that you opened with master branch which is perhaps protected?

a few tests hang but I suspect they're are related to infura/goerli rpc keys.
so before we continue we need to update those, ref https://github.com/foundry-rs/foundry/pull/4781

but this looks pretty good, can merge once tests green!

2023-04-27 19:17 UTC, Evalir commented
Aight all tests seem to be fixed but CI is hanged on this last one (`test_cmd::can_test_forge_std`). As you mentioned @mattsse it could probably be the keys—how should we proceed?

2023-04-28 14:27 UTC, mattsse approved these changes
alright, let's do a final rebase then send it

2023-04-29 07:03 UTC, merged

2023-04-30 00:03 UTC, sambacha commented
I christen thee, v1.0.0