fix(forge): update forge remove
foundry-rs/foundry pull request #4767
Opened 2023-04-18 18:05 UTC by DaniPopes

## Motivation

- Calling `rm` command...

- Use `git rm path/to/submodule`. See: <https://stackoverflow.com/a/1260982>

## Solution

2023-04-18 18:26 UTC, mattsse requested changes

2023-04-18 18:26 UTC, mattsse commented on cli/src/opts/dependency.rs
> +        self.alias.as_ref().unwrap_or(&self.name)
```suggestion
    pub fn name(&self) -> &str {
        self.alias.as_deref().unwrap_or(self.name.as_str())
```

2023-04-18 18:26 UTC, mattsse commented on cli/src/cmd/forge/remove.rs
> -                .exec()?;
why do we no longer need this?

2023-04-18 18:26 UTC, mattsse commented on cli/src/cmd/forge/remove.rs
> -                .exec()?;
nvm read the linked SO post

2023-04-18 18:35 UTC, DaniPopes commented on cli/src/opts/dependency.rs
> +        self.alias.as_ref().unwrap_or(&self.name)
Meh it's the same for return types

2023-04-18 18:38 UTC, mattsse approved these changes

2023-04-19 06:34 UTC, mattsse approved these changes

2023-04-19 06:34 UTC, merged

2023-04-19 07:42 UTC, mattsse commented
@DaniPopes I reverted this because merged carelessly, this didn't pass the existing install+remove tests, sorry about this.

feel free to reopen this 

I think we need a separate job for all the repro tests because they use rpc calls and are very flaky

2023-04-19 12:55 UTC, DaniPopes commented
I see, before we always removed the dependency, while now `git rm` won't remove it when there are uncommitted changes etc like in other commands:

![image](https://user-images.githubusercontent.com/57450786/233080279-d4e77cf8-4e45-45d8-83a4-2719485f023b.png)

I think it's better this way, with a `--force|-f` option like in `forge init`.

2023-04-19 13:02 UTC, DaniPopes commented
It will also not remove the directory in `.git/modules/`, I don't know if this is necessary

2023-04-19 13:11 UTC, mattsse commented
> It will also not remove the directory in .git/modules/, I don't know if this is necessary

I see, so this can be reapplied after tests are updated?