Enable decoding non-Ethereum precompiles when tracing
foundry-rs/foundry pull request #4821
Opened 2023-04-25 17:22 UTC by 4meta5

Enable decoding calls from non-Ethereum precompiles when tracing https://github.com/foundry-rs/foundry/issues/1078 by adding a field to `foundry_config::Config` for `precompiles: Vec<(Address, Function)>`. Not sure yet where the required non-Ethereum precompile data (`Vec<(Address, Function)>`) should live, please provide feedback.

## Motivation

Enable decoding calls from non Ethereum precompiles when tracing https://github.com/foundry-rs/foundry/issues/1078

## Solution

Define `with_precompiles` method on `CallTraceDecoderBuilder` to augment the Ethereum precompiles included in `new` method  with non-Ethereum precompiles specified by a config.

2023-04-26 11:11 UTC, mattsse requested changes

2023-04-26 11:11 UTC, mattsse commented on config/src/lib.rs
> +    pub precompiles: Vec<(Address, Function)>,
this is reasonable,

I'd like to see some tests/examples for this in toml format

2023-04-26 20:27 UTC, 0xMelkor commented on evm/src/trace/decoder.rs
> +        self.decoder.precompiles = self.decoder.precompiles.into_iter().chain(precompiles).collect();
I'd keep `CallTraceDecoder`'s  encapsulation safe. 
How if: 
```rust
impl CallTraceDecoder {
  pub fn chain(&mut self, precompiles: HashMap<Address, Function>) {
     ...
  }
}
```

2023-08-16 00:10 UTC, Evalir approved these changes
should be good now—just needs examples

2023-09-25 21:37 UTC, Evalir commented
Will close this—while "complete", it's a pretty sensitive change that will get overwritten by the alloy migration, and on top of this we're still debating a bit on how to include these external precompiles. Once the migration is done we can include a configuration option to detect and decode these.

2023-09-25 21:37 UTC, closed without merging