Invariants feat: add config option to turn off shrinking
foundry-rs/foundry pull request #4868
Opened 2023-05-02 19:11 UTC by grandizzy

## Motivation

See https://github.com/foundry-rs/foundry/issues/4867, when running invariants test with many runs and depth (1000) the test hangs in shrinking scenario (performed for each invariant). In this case sometimes is preferable to fail fast and address the issue.

## Solution

* add try_shrinking config in [invariant], default true, tries to reduce number of calls in scenario to min
* when set to false test will fail fast and output the original number of calls in scenario

2023-05-03 12:51 UTC, mds1 commented
@0xmelkor note that we'll need to update https://github.com/foundry-rs/foundry/pull/4744 to support this option in there too

2023-05-03 17:57 UTC, 0xMelkor commented
> @0xMelkor note that once this is merged we'll need to update #4744 to support this option in there too

Hi @mds1, sure.

2023-05-04 17:41 UTC, mattsse requested changes
smol nit, otherwise lgtm

2023-05-04 17:41 UTC, mattsse commented on evm/src/fuzz/invariant/error.rs
> +            trace!(target: "forge::test", "Shrinking disabled.");
please remove `_` prefix

2023-05-04 17:55 UTC, grandizzy commented
> smol nit, otherwise lgtm

yep, added such to avoid `warning: unused variable: if this is intentional, prefix it with an underscore` is there a different preferred way to disable this?

2023-05-04 18:01 UTC, mattsse commented
but 

> `let _calls =`

`let _calls = self.try_shrinking(_calls, &executor);`

so I think it should be `let calls = ...; let _ self.try_shrinking(calls,&executor)`

2023-05-04 18:05 UTC, grandizzy commented
> but
> 
> > `let _calls =`
> 
> `let _calls = self.try_shrinking(_calls, &executor);`
> 
> so I think it should be `let calls = ...; let _ self.try_shrinking(calls,&executor)`

oops, right, changing

2023-05-04 18:30 UTC, grandizzy commented
> > but
> > > `let _calls =`
> > 
> > 
> > `let _calls = self.try_shrinking(_calls, &executor);`
> > so I think it should be `let calls = ...; let _ self.try_shrinking(calls,&executor)`
> 
> oops, right, changing

fixed with https://github.com/foundry-rs/foundry/pull/4868/commits/022646173af48b63cbf76d98ebf1a90d1039c597

2023-05-11 22:25 UTC, mattsse approved these changes
cool, tysm!

lgtm!

2023-05-12 00:01 UTC, Evalir approved these changes
LGTM! Just pushed something upstream to make it compatible with #4744. Nice work!

2023-05-12 00:01 UTC, Evalir commented on config/src/invariant.rs
> +                "shrink-sequence" => conf_clone.shrink_sequence = parse_config_bool(key, value)?,
added the new `shrink-sequence` key to the invariant inlineconfigparser so it works with #4744

2023-05-12 15:03 UTC, mattsse approved these changes

2023-05-12 15:03 UTC, merged

2023-05-12 15:22 UTC, grandizzy commented
thank you all!