fix(forge): sensitive broadcast logs
foundry-rs/foundry pull request #4892
Opened 2023-05-07 17:18 UTC by devanoneth

## Motivation

Remove sensitive values from broadcast logs. Namely `rpc` and `path`. Fixes #4730.

## Solution

As proposed in #4730, saves sensitive values into a file with the same name / folder path but instead of the `broadcast` dir, we use the `cache` dir. It introduces a `ScriptSequenceSensitive` struct which can be used to write sensitive values and later load them back into the `ScriptSequence` struct.

Also fixes and extends the `check_broadcast_log` test so the changes can be tested.

2023-05-09 01:46 UTC, Evalir reviewed
Hey hey thanks for this!

logic looks ok, but haven't tested. some nits re docs/comments/naming:

2023-05-09 01:46 UTC, Evalir commented on cli/src/cmd/forge/script/sequence.rs
>              shell::println(format!("\nTransactions saved to: {path}\n"))?;
maybe we should print an extra message indicating sensitive info has been written to a separate path?

2023-05-09 11:09 UTC, devanoneth commented on cli/src/cmd/forge/script/sequence.rs
> +pub struct ScriptSequenceSensitive {
Would `SensitiveScriptSequence` be better? I wanted to keep the name close to the `ScriptSequence` struct as that's where these values come from.

That way you have your `ScriptSequence` which can be committed and `SensitiveScriptSequence` which shouldn't be.

2023-05-09 23:35 UTC, Evalir commented on cli/src/cmd/forge/script/sequence.rs
> +pub struct ScriptSequenceSensitive {
Yep, this sounds good!

2023-05-10 10:54 UTC, devanoneth commented on cli/src/cmd/forge/script/sequence.rs
> +pub struct ScriptSequenceSensitive {
Cool, that's already in my last commit :)

2023-05-12 02:37 UTC, Evalir commented
hey hey, will TAL tomorrow and hopefully merge this! looks solid, just haven't fully tested yet

2023-05-12 09:31 UTC, devanoneth commented
No prob @Evalir, you're smashing PRs out lately! <3

2023-05-13 04:42 UTC, Evalir approved these changes
this lgtm!
ptal @mattsse

2023-05-17 14:47 UTC, mattsse requested changes
cool!

test lgtm!

@Evalir do we need to put this in the changelog?

I believe we need to add this to the default gitignore as well?

2023-05-18 00:02 UTC, devanoneth commented
@mattsse thanks for reviewing! I'm not sure why this would need changes in the default `.gitignore`? I just checked and it ignores `cache` and doesn't ignore `broadcast` for any chain without id `31337`:

```
# Compiler files
cache/
out/

# Ignores development broadcast logs
!/broadcast
/broadcast/*/31337/
/broadcast/**/dry-run/

# Docs
docs/

# Dotenv file
.env
```

2023-05-18 11:53 UTC, mattsse commented
I see, so the senstive logs are always ignored?

2023-05-18 12:02 UTC, devanoneth commented
@mattsse Yeah, the sensitive logs go into directories under the cache directory. See the `get_paths` function in `sequence.rs` for more details.

2023-05-18 13:08 UTC, mattsse approved these changes
gg

2023-05-18 13:08 UTC, merged