feat(cheatcodes): `tryFfi` cheatcode
foundry-rs/foundry pull request #4908
Opened 2023-05-09 16:53 UTC by Evalir

## Motivation

Closes #2932 .

## Solution

Adds a `tryFfi` cheatcode, which returns a `FfiResult` struct which contains:
- The `exit_code`
- The `stdout` as bytes.
- The `stderr` as bytes.

2023-05-09 16:55 UTC, Evalir commented on testdata/cheats/TryFfi.t.sol
> +        Cheats.FfiResult memory f = cheats.tryFfi(inputs);
Currently debugging why this is reverting with a cryptic `EVMError: Revert` error. While the `try_ffi` function for the cheatcode works well and returns the data normally, it seems to be causing a revert down the line.

2023-05-20 11:52 UTC, mattsse requested changes
sorry forgot to review this.

I like this, but it needs a rebase because we moved cheatcodes

2023-06-09 11:29 UTC, mattsse reviewed
looks like this just needs a rebase?

2023-06-15 20:55 UTC, mattsse approved these changes

2023-06-15 20:56 UTC, mattsse commented
there's a failing test, otherwise lgtm

2023-06-15 21:26 UTC, Evalir commented
yeah need to debug why this is failing—the cheatcode actually always reverts for some reason. need to test further before merge

2023-08-18 16:45 UTC, closed without merging