Script: ensure prevrandao is set, even if no mixHash in response
foundry-rs/foundry pull request #4924
Opened 2023-05-11 15:14 UTC by 0xCalibur

## Motivation
ref https://github.com/foundry-rs/foundry/issues/4238

ensure prevrandao is set, even if no mixHash in response

## Solution
same fix as anvil but when running forge script.

2023-05-11 17:47 UTC, DaniPopes requested changes

2023-05-11 22:22 UTC, mattsse requested changes
this doesn't compile, 

please put this in a `Some`

please consider enabling changes by maintainer

2023-05-12 13:03 UTC, 0xm3rlin commented
> this doesn't compile,
> 
> please put this in a `Some`
> 
> please consider enabling changes by maintainer

the opposite might be helpful as the changes by @DaniPopes @Evalir were errorful.

i would suggest reverting this pr back to the original commit 50212024e134b4117b17145e3999bf14e775418a by @0xCalibur

2023-05-12 13:06 UTC, Evalir commented
hey @0xm3rlin — yeah we committed a suggestion which was errorful. That being said, we can't push to this branch as the PR comes from the fork's master, which is protected. Happy to merge this ASAP if @0xCalibur fixes it—it's just a one line change. If not happy to close and reopen on another PR to merge this quickly.

2023-05-12 13:26 UTC, 0xCalibur commented
> hey @0xm3rlin — yeah we committed a suggestion which was errorful. That being said, we can't push to this branch as the PR comes from the fork's master, which is protected. Happy to merge this ASAP if @0xCalibur fixes it—it's just a one line change.

I'm confused...so I just need to go back to the original changes?

2023-05-12 13:36 UTC, Evalir requested changes

2023-05-12 14:48 UTC, mattsse approved these changes
okay, after several rounds of reviews for this one liner, I think we finally figured it out -.-

2023-05-12 14:48 UTC, mattsse commented on evm/src/executor/fork/init.rs
> +            prevrandao: Some(block.mix_hash.unwrap_or_default()),
```suggestion
            prevrandao: Some(block.mix_hash.map(u256_to_ru256).unwrap_or_default()),
```

2023-05-12 14:56 UTC, mattsse commented
well, this has been more effort than expected lol

I'm closing this, and pushed changes manually to #4929

can't make changes manually here since this is opened from master branch

2023-05-12 14:56 UTC, closed without merging

2023-05-12 20:45 UTC, DaniPopes commented
oops