Expose storage altering functions in EVM Executor Backend
foundry-rs/foundry pull request #5351
Opened 2023-07-10 19:47 UTC by ArielTM

## Motivation

Working with Foundry EVM Executor, one can alter balance, nonce and code of an account, but not the storage.

## Solution

This PR exposes two functions
1. `active_fork_db_mut` will be `pub` (same as `active_fork_mut`)
2. Added the function `insert_account_storage` to the Backend

2023-07-10 20:56 UTC, mattsse requested changes
reasonable,

doc nit

2023-07-10 20:56 UTC, mattsse commented on evm/src/executor/backend/mod.rs
> +    pub fn insert_account_storage(
needs one-liner doc

2023-07-10 22:56 UTC, Evalir approved these changes
thank you! should be useful.

2023-07-10 23:03 UTC, mattsse approved these changes

2023-07-11 10:22 UTC, ArielTM commented
Is there anything needed to merge this?

2023-07-12 10:16 UTC, mattsse commented
nope, just forgot -.-

2023-07-12 10:16 UTC, merged