feat(`forge`): support for `console.log` on Invariant handlers
foundry-rs/foundry pull request #5488
Opened 2023-07-27 22:04 UTC by Evalir

## Motivation

Closes #4951 

## Solution

Adds support for console logs on invariant handlers, by persisting the logs and traces for the last call.

To avoid any performance regressions we only move values and only copy where absolutely necessary (filling each invariant with the corresponding logs at the end), and only persist the call values at the end of each run campaign, as they would just be overwriting values persisted at the heap otherwise.

2023-07-27 22:48 UTC, Evalir commented
hey hey @mds1 mind sanity testing this too? this is a highly requested feature so wanna make sure all is good ^^

2023-07-27 22:49 UTC, mds1 commented
For sure, again tagging @lucas-manuel and @PaulRBerg for testing assistance too 😁

2023-07-28 18:01 UTC, mattsse requested changes
smol nit

2023-07-28 18:01 UTC, mattsse commented on evm/src/fuzz/invariant/executor.rs
> +
I'd prefer a helper struct for this, makes changing it easier

2023-08-10 07:08 UTC, Evalir commented
cc @mattsse this should be good for another review round—functionality is sound

2023-08-10 10:29 UTC, mattsse approved these changes

2023-08-10 10:29 UTC, merged