Pass details on GasTooHigh
foundry-rs/foundry pull request #5489
Opened 2023-07-27 23:17 UTC by aathan

## Motivation

GasTooHigh errors were too opaque and I could not tell what was generating the GasTooHigh error.

## Solution

Made the GasTooHigh variant a struct with a string that could carry details.

2023-07-29 00:41 UTC, Evalir requested changes
looks good bar some nits. wdyt @mattsse ?

2023-07-29 00:41 UTC, Evalir commented on anvil/src/eth/backend/mem/mod.rs
> +                detail: String::from("tx.gas_limit>env.block.gas_limit"),
```suggestion
                detail: String::from("tx.gas_limit > env.block.gas_limit"),
```

2023-07-29 00:41 UTC, Evalir commented on anvil/src/eth/error.rs
> +    GasTooHigh(ErrDetail),
Hmm, i think we could have just a `String` here—if we wanna name it a bit more fancily we can just make a type like `type GasErrorDetail = String;`.

2023-08-01 18:14 UTC, Evalir approved these changes

2023-08-01 18:42 UTC, mattsse approved these changes

2023-08-01 18:42 UTC, merged