wip:fix: handle duplicate forkids
foundry-rs/foundry pull request #5939
Opened 2023-09-28 12:03 UTC by mattsse

Closes #5935

we have an edge case with forkids internally that can lead to an out of bounds bug if the same URL is used twice and the local mapping is updated

https://github.com/foundry-rs/foundry/blob/master/crates/evm/src/executor/backend/mod.rs#L1624-L1634

2023-09-29 02:14 UTC, frank-lim-partior commented
The expected behavior is that `forkId1 != forkId2`, is that correct? I had hoped to use this to test contracts across 2 different forks from the same state.

2023-09-29 09:59 UTC, mattsse commented
this is rather a bug how me map the assigned uint256 forkids internally, because both forking off the same endpoint at the same height, so we need to change how we keep track of those, will fix shortly

2023-11-07 13:47 UTC, DaniPopes commented
@mattsse ping

2023-11-28 10:54 UTC, mattsse commented
@DaniPopes whoops, totally forgot about this.

I took a page out of the cargo playbook and used an URL hack to make them unique, this was easier than rewriting the internal mappings...
This is not ideal but at least fixes the issue, the fact that we only got one report so far indicates that this is not a common pattern so the fix should be fine

2023-11-28 11:43 UTC, DaniPopes requested changes

2023-11-28 11:43 UTC, DaniPopes commented on crates/forge/tests/it/repros.rs
> +test_repro!(5935);
order :)

2023-11-28 12:58 UTC, DaniPopes approved these changes

2023-11-28 13:08 UTC, merged