[Draft] Add vm.time() cheatcode
foundry-rs/foundry pull request #5952
Opened 2023-09-29 08:13 UTC by Tudmotu

## Motivation
Fixes #5937.
For long-running scripts it is sometimes useful to measure certain parts and analyze their performance in order to optimize running time. `block.timestamp` does not provide a real-time system timestamp, and using `date` via `ffi` is not granular enough due to Mac OS lack of milliseconds support.

This feature will return an accurate timestamp, in milliseconds since unix epoch, as `uint`.

## Solution
I've added the usual cheatcode components:
- Added function to `HEVM.sol`
- Generated abi bindings
- Added implementation to `foundry-evm` (specifically, `ext.rs`)
- Added Solidity tests in `testdata`

Implementation details:
- Using `SystemTime::now().duration_since(UNIX_EPOCH)`, following the [example from the docs](https://doc.rust-lang.org/std/time/struct.SystemTime.html#impl-SystemTime)
- Converting `u128` to `Bytes` via `rU256` 

## Open questions
- The following test fails both on my branch and on master: `'otterscan::can_call_ots_has_code'`.
Is this ok?
- Using`rU256` to convert the `u128` from `.as_millis()` to bytes — is there a nicer way to achieve this?
- Should this be renamed to something else, such as `.unixTime()`, `.systemTime()` or `.timestamp()`? Personally I would have preferred `vm.now()` but `now` is a reserved word in Solidity

2023-09-29 10:09 UTC, mattsse requested changes
cool, I like this,

smol nits

2023-09-29 10:09 UTC, mattsse commented on crates/evm/src/executor/inspector/cheatcodes/ext.rs
> +fn time() -> Result {
let's call this duration_since_epoch

2023-09-29 10:09 UTC, mattsse commented on crates/evm/src/executor/inspector/cheatcodes/ext.rs
> +    Ok(Bytes::from(as_u8_arr))
we need to encode this, types are currently a bit horrible until we completely transitioned to alloy types we need to use:
`Ok(rU256::from(millis).to_ethers().encode().into())`

2023-09-29 10:44 UTC, Tudmotu commented
Thanks @mattsse for the review, will make the changes and update :slightly_smiling_face:

2023-09-29 13:05 UTC, Tudmotu commented
@mattsse I have addressed your comments and also went ahead and changed the cheatcode to `unixTime()`.
Can still modify it if there's any objection to that name.

2023-10-01 00:15 UTC, Evalir approved these changes
personally don't have typos—as long as this test passes I think this is good! deferring to @mattsse & @mds1 for merge (also needs `cargo +nightly fmt`)

2023-10-01 06:30 UTC, Tudmotu commented
Apologies, I messed up the format in the last change and forgot to fix it.
Pushed a fix now.

2023-10-02 02:25 UTC, Evalir approved these changes
let's remember to update the book & forge-std once this is merged!

2023-10-02 05:53 UTC, Tudmotu commented
@Evalir I already got foundry book & forge-std updates prepared, just waiting for this to be merged before I open PRs :slightly_smiling_face:

2023-10-02 11:42 UTC, mattsse approved these changes
lgtm, tysm!

2023-10-02 11:42 UTC, merged

2023-10-02 12:56 UTC, Tudmotu commented
Thank you all, you're doing amazing work with Foundry. And I must add the PR process was very smooth, well done! :clap: