feat: Add `loadAllocs` cheatcode
foundry-rs/foundry pull request #6101
Opened 2023-10-25 00:08 UTC by clabby

## Overview

Introduces a new cheatcode, `loadAllocs`, which allows for directly inserting accounts into the in-memory revm state from an `allocs` section of a standard `genesis.json` file.

## Motivation

Several Layer 2s, including Optimism, allocate _many_ proxies etc. in the genesis file. For example, take [Base Mainnet's 8.76MB genesis file](https://github.com/base-org/node/blob/main/goerli/genesis-l2.json).

While it is possible to deploy all of these contracts manually in a test file's `setUp` function, it is slow, cumbersome, and rather easy to accidentally break parity.

## Solution

To allow for quicker and more ergonomic test setups in situations like the above, I've added a new `loadAllocs` cheatcode. This takes a path to a JSON file containing only the `allocs` object within a standard `genesis.json`, and directly inserts these accounts into revm's journal.

**Alloc File Schema**

The alloc file is simply the `allocs` section of a standard Genesis JSON file - that is, `HashMap<Address, GenesisAccount>`, where `GenesisAccount` is defined in `ethers-rs` as:

```rs
/// An account in the state of the genesis block.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct GenesisAccount {
    #[serde(
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_stringified_u64_opt",
        default
    )]
    pub nonce: Option<u64>,
    #[serde(deserialize_with = "deserialize_stringified_numeric")]
    pub balance: U256,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub code: Option<Bytes>,
    #[serde(
        skip_serializing_if = "Option::is_none",
        deserialize_with = "from_unformatted_hex_map",
        default
    )]
    pub storage: Option<HashMap<H256, H256>>,
}
```

## Testing

Accompanying tests for the new cheatcode have been added in `testdata`.

2023-11-01 18:34 UTC, DaniPopes commented on crates/cheatcodes/src/impls/evm.rs
> +    }
can you please keep style consistent with the rest of the cheatcodes here? `Self` destructure at the top and lowercase error message.

2023-11-01 18:35 UTC, DaniPopes requested changes

2023-11-01 18:35 UTC, DaniPopes commented on crates/evm/evm/src/inspectors/cheatcodes/snapshot.rs
This folder does not exist anymore

2023-11-03 20:22 UTC, Evalir commented
Closing in favor of #6207

2023-11-03 20:22 UTC, closed without merging