fix(forge): add coverage to test setUp
foundry-rs/foundry pull request #6123
Opened 2023-10-26 14:26 UTC by Inphi

## Motivation

Improve forge coverage reporting of functions called during test `setUp`. This allows initializer functions to be covered, but not ctors, called during setUp (ex: https://github.com/foundry-rs/foundry/issues/4553). 

## Solution

The `TestSetup` is extended to include coverage info. The `setUp` coverage is then merged with `HitMaps` generated by test runners.

2023-10-31 15:20 UTC, Evalir reviewed
This looks reasonable—Is it possible for you to provide a screenshot of this working when using lcov or something similar for vis? Just to ensure everything looks okay.

2023-10-31 15:21 UTC, Evalir requested changes
this will also need rebasing—sorry about this, lots of moving parts rn, we'll be done soon!6

2023-11-01 15:05 UTC, Inphi commented
@Evalir Thanks for the review. PR's been rebased and I've added a visual description of this change.

2023-11-01 19:30 UTC, Evalir requested changes
nice, looks reasonable, and tests look good. Pending @mattsse and nit

2023-11-01 19:30 UTC, Evalir commented on crates/forge/src/runner.rs
> +// Utility function to merge coverage options
```suggestion
/// Utility function to merge coverage options
```

2023-11-02 14:09 UTC, Evalir approved these changes

2023-11-03 15:24 UTC, merged