refactor: migrate to alloy providers
foundry-rs/foundry pull request #6219
Opened 2023-11-05 21:16 UTC by onbjerg

## Motivation

We want to migrate from Ethers to Alloy, which includes removing all references to Ether's `Middleware` trait and using Alloy equivalents (`alloy-providers`).

## Solution

The API for providers is not final, so a temporary trait has been introduced to make migrating to the final API easier later on. Additionally, I will be removing code that is no longer needed (e.g. `RuntimeClient`), as well as adjusting everything that breaks downstream as a result of me changing the providers (e.g. `forge script`).

## Todo

- Adjust tests
- Adjust docs
- Resolve final breakages
- Open up issues re: ergonomics with Alloy encountered during migration
- Implement WebSocket and IPC support

2023-12-13 15:59 UTC, onbjerg commented on crates/common/src/provider/alloy.rs
> +        // todo: port poll interval hint
not relevant rn since we don't poll anything using this provider, but good to remember for later when we migrate cast

2023-12-15 15:11 UTC, Evalir approved these changes
Need to give this a final final review, but we should way until after this weekend to merge this to avoid any potential snafus with any small breakages we might face not covered by CI.

2023-12-18 10:58 UTC, DaniPopes requested changes

2023-12-18 17:24 UTC, onbjerg commented on crates/anvil/src/eth/backend/fork.rs
> +        // let interval = self.provider.get_interval();
doesn't exist in alloy and is not needed for anvil because we do not do subscriptions of any kind

2023-12-21 00:41 UTC, gakonst commented
blocked on https://github.com/alloy-rs/alloy/pull/89 to ensure that we can move Reth Inspectors to use Alloy RPC instead of Reth RPC to avoid cyclical deps / incompats

2024-01-04 19:19 UTC, Evalir commented
Unblocked thru https://github.com/alloy-rs/alloy/pull/89, https://github.com/alloy-rs/alloy/pull/96 & https://github.com/alloy-rs/alloy/pull/97, next step is to use the updated alloy-rpc-types to make this compile, and after, a rebase.

2024-01-05 18:05 UTC, mattsse requested changes
okay, we need another pass and remove alloy ethers conversion where possible

2024-01-05 18:14 UTC, Evalir commented on crates/anvil/src/eth/backend/mem/storage.rs
>              difficulty: env.block.difficulty.to_ethers(),
These are storage-related types and we agreed not to migrate them on this PR.

2024-01-05 18:16 UTC, Evalir commented on crates/anvil/src/eth/api.rs
> +        self.backend.cheats().is_impersonated(addr.to_ethers())
Also an storage type.

2024-01-05 18:18 UTC, Evalir commented on crates/anvil/src/eth/api.rs
> +        if let &BlockRequest::Number(number) = &block_request {
https://github.com/foundry-rs/foundry/pull/6219/commits/cba1d937b03ba464ea576a0c1f5dc6fc452027db

2024-01-05 18:43 UTC, Evalir commented on crates/anvil/src/pubsub.rs
> +                let receipts = self.storage.receipts(block.hash.to_alloy());
https://github.com/foundry-rs/foundry/pull/6219/commits/2f3ebba0a9c5b0f6e8b87c54ef608617234494ae

2024-01-05 18:44 UTC, Evalir commented on crates/anvil/src/config.rs
> +        );
https://github.com/foundry-rs/foundry/pull/6219/commits/2f3ebba0a9c5b0f6e8b87c54ef608617234494ae

2024-01-05 19:55 UTC, mattsse approved these changes
more things to come!

2024-01-08 12:07 UTC, onbjerg commented
I've tried looking at the ICE but I don't think there's a workaround. Should we merge with the ICE present?

2024-01-08 13:43 UTC, Evalir commented
yep @onbjerg we can safely ignore the ICE for now—clippy won't run anyway until it's fixed.

2024-01-08 13:48 UTC, merged