feat(cast/bin) : convert value to decimal and add hex value table
foundry-rs/foundry pull request #6333
Opened 2023-11-16 18:43 UTC by DoTheBestToGetTheBest

- currently we're printing value as hex and it is supposed to be decimal, this pr convert hex to dec
-  added hex value table

2023-11-16 21:20 UTC, DaniPopes requested changes

2023-11-16 21:20 UTC, DaniPopes commented on crates/cast/bin/cmd/storage.rs
> +        let hex_value = format!("{:x}", &value);
these dont need separate variables, and use to_string instead of format

2023-11-17 13:14 UTC, DaniPopes approved these changes

2023-11-17 13:42 UTC, Evalir approved these changes

2023-11-17 14:01 UTC, merged