RPC-based Gas Estimation for Moonbeam-based Networks
foundry-rs/foundry pull request #6460
Opened 2023-11-29 17:17 UTC by albertov19

## Motivation

Moonbeam introduced MBIP-5 in which gas estimation deviated from Ethereum. The reasoning is that now storage changes are reflected now on gas estimation. This is to prevent spamming the network with junk data. This is a problem on a lot of cheap-to-transact networks

## Solution

Solution was simple, just add Moonbeam-based networks to the `has_different_gas_calc` function (like with Arbitrum) [here](https://github.com/foundry-rs/foundry/compare/master...albertov19:foundry:albertov19/use-rpc-gas-estimation-moonbeam)

If this function returns `true` then gas estimation is done using the actual provider URL and `eth_estimateGas`.

2023-11-29 18:24 UTC, mattsse requested changes
~~the outlined solution makes sense, though I think you forgot to include it here :)~~

2023-11-29 18:24 UTC, mattsse requested changes
please restore other formatting issues like trailing ;

2023-11-29 18:24 UTC, mattsse commented on crates/cli/src/utils/cmd.rs
> +                | NamedChain::MoonbeamDev
ah nvm, I overlooked it hehe

2023-11-29 21:47 UTC, Evalir requested changes
looks good, pending mattsse's nit

2023-11-29 22:20 UTC, albertov19 commented
@mattsse @Evalir thanks! I think it should be good. Everything was added by the `cargo fmt` command, I just reverted the `;`

2023-11-30 10:47 UTC, albertov19 commented
Ah apologies I did not understand you wanted me to revert the `|` change as well - This should be ready to go right?

I tested this implementation in a local Foundry Forge instance and it worked btw.

2023-11-30 11:08 UTC, mattsse approved these changes
lgtm

2023-11-30 11:22 UTC, merged