feat(forge): added --json argument to `forge build` command
foundry-rs/foundry pull request #6465
Opened 2023-11-30 03:10 UTC by 0xMemoryGrinder

This PR adds a `--json` argument to `forge compile` command to output the compilation warnings/errors in json

## Motivation

Currently integrating foundry in VSCode, my team and I quickly realized there is no output format that can be  easily parsed for the `forge compile` command. The goal is thus to add a `json` to output the compilaton result in the JSON format.

## Solution

To implement this feature, I added a `json` field in the `BuildArgs` structure and added a condition in the run method of the command to check if the argument has been used. 

If so, a new function `suppress_compile_with_filter_json` is called. It behaves like the `suppress_compile_with_filter` function but without throwing error when compilation errors arise. 

All the other modified files are due to the new function parameters which I added to indicate to the function whether to throw or not.

## Additional comments

I not sure if I should have add the `json` argument in the `BuildArgs` structure or in the `CoreBuildArgs` structure. Let me know if I should fix this.

This PR does not contain test for the new feature as I only rely on serde_json and there was no tests for the compile command beforehand.

2023-11-30 12:40 UTC, mattsse requested changes
supportive, I can see how this is useful.

smol nits

> or in the CoreBuildArgs structure

the new flag should stay in BuildArgs, because it's build command specific. other commands also have a json flag, like test which would then conflict if we have it in CoreBuildArgs

we also want a test for this:

add new `tests/it/build.rs` file, add contract that has an error, run build command, check output.

ref example test you can use as base
https://github.com/foundry-rs/foundry/blob/e26f4d8585cc543dea8aa719ab89426fc17fcdaa/crates/forge/tests/cli/test_cmd.rs#L52-L71

you can generate fixtures via `cmd.write_fixtures(path)` and then use it

2023-11-30 12:40 UTC, mattsse commented on crates/forge/bin/cmd/build.rs
> +    ///Output the compilation errors in the json format.
```suggestion
    /// Output the compilation errors in the json format.
```

2023-11-30 12:40 UTC, mattsse commented on crates/forge/bin/cmd/build.rs
> +    #[clap(long)]
this should conflict with `silite`, "conflicts_with = "silent"" should work I believe, but better add a parser test as well:

ref https://github.com/foundry-rs/foundry/blob/e26f4d8585cc543dea8aa719ab89426fc17fcdaa/crates/forge/bin/cmd/build.rs#L151-L151

2023-11-30 12:40 UTC, mattsse commented on crates/common/src/compile.rs
> +pub fn suppress_compile(project: &Project, throw_err: bool) -> Result<ProjectCompileOutput> {
not a fan of this solution,

I'd like to add this feature as an additional function

`fn try_suppress_compile` that simply doesn't check the compiler errors. `suppress_compile` can then call this and apply the error check

2023-11-30 20:23 UTC, 0xMemoryGrinder commented
Thank you for your valuable feedback @mattsse. I implemented all your requests. Let me know if I can do something else

2023-12-01 13:06 UTC, mattsse requested changes
this looks great!

I'd like to see a simple test case for json output, see instructions above

2023-12-01 16:35 UTC, 0xMemoryGrinder commented
Does the one in `crates/forge/test/cli/build.rs` not fulfill your requirements ? 
I implemented it following your above advice.

2023-12-01 17:23 UTC, mattsse approved these changes
my bad, I must have overlooked this, hehe

2023-12-01 18:22 UTC, DaniPopes approved these changes

2023-12-01 18:43 UTC, merged

2026-06-19 09:12 UTC, Alexis98MG approved these changes