feat: add additional snapshot cheatcodes
foundry-rs/foundry pull request #6548
Opened 2023-12-08 10:07 UTC by mattsse

ref #6411

since we're persisting snapshots on `revertTo` we have unbounded memory growth.
We want to keep them for convenience, so we need additional cheatcodes to handle cleanup:

* revertToAndDelete (I picked this one over overloading `revertTo`, not sure what would be the best UX, but we could add an overloaded function as well (id, bool))
* deleteSnapshot
* deleteSnapshots

2023-12-09 06:34 UTC, Evalir requested changes
smol nit

2023-12-09 06:34 UTC, Evalir commented on crates/cheatcodes/spec/src/vm.rs
> +    /// Takes the snapshot ID to delete.
I think it'd be useful to document what happens if the snapshot ID passed in does not exist

2023-12-10 20:14 UTC, Evalir approved these changes

2023-12-11 00:47 UTC, DaniPopes approved these changes

2023-12-11 01:28 UTC, merged

2023-12-22 11:45 UTC, maa105 commented
Awesome thanks a million!