Copy verified source contract from one blockexplorer to another
foundry-rs/foundry pull request #6685
Opened 2023-12-30 06:21 UTC by ckoopmann

## Motivation

Recently I ran into the issue where I wanted to get a bunch of contracts verified on Blockscout, which were already verfied on etherscan. For some of these contracts I did not have ready access to the original source code repo, so it would have been difficult / tedious to verify them manually.

## Solution

 I wrote a little script that downloads the source code / metadata from the source explorer (etherscan in that case) and then uses that data to verify the contracts on the target explorer.

I thought this might be interesting for other people as well so I turned it into a [crate](https://crates.io/crates/contract-verification-migrator) and extended the cast cli to include this functionality.

## Demo

![demo](https://github.com/foundry-rs/foundry/assets/15629702/bbcdbcad-23e2-4002-940d-072dac459148)

2024-01-03 15:33 UTC, Evalir requested changes
Hey! thanks a lot for this—the implementation looks good to me, but this can be easily done with the crate itself, so I'm not super sold on adding this to cast as this means another dependency we have to add that basically does all the work for us, and this is a very niche use case.

I'll defer to maybe @mds1 to decide if we should include this in cast

2024-01-04 07:43 UTC, ckoopmann commented
> Hey! thanks a lot for this—the implementation looks good to me, but this can be easily done with the crate itself, so I'm not super sold on adding this to cast as this means another dependency we have to add that basically does all the work for us, and this is a very niche use case.
> 
> I'll defer to maybe @mds1 to decide if we should include this in cast

Thanks for the feedback. I agree that the cast integration does not add additional value / functionality over using the crate directly. It just makes it more accessible for users who have cast already. It is a bit of a "plug" though tbh, so I understand if you guys want to avoid feature creep / excessive dependencies.

2024-01-04 13:54 UTC, Evalir commented
yep sounds good @ckoopmann — apologies for this! i'll close for now, mainly because this is a super niche use case rather than a plug (plugs are fine if the tool is super useful)—if we see an issue to do this, happy to reopen & merge!

2024-01-04 13:54 UTC, closed without merging

2024-01-09 02:08 UTC, mds1 commented
This is cool and does seem useful, but agreed it's niche and not needed in cast. But perhaps worth linking to this tool on a contract verification page in the book to aid discoverability, since I can see the need arising during verification flows? (Probably should also include a disclaimer that it's a third party tool not verified by the foundry team too)