feat: LogCollector use alloy_rpc_types::Log
foundry-rs/foundry pull request #6752
Opened 2024-01-10 09:09 UTC by qiweiii

## Motivation

resolve: #6746

## Solution

2024-01-10 09:19 UTC, qiweiii commented
hi @mattsse, are my changes the expected solution?

2024-01-10 09:26 UTC, mattsse requested changes
yep, this is great!

only smol nits

2024-01-10 09:26 UTC, mattsse commented on crates/forge/tests/it/repros.rs
> +            .collect(),
this should use `to_ethers()` for now I believe

2024-01-10 09:26 UTC, mattsse commented on crates/evm/evm/src/inspectors/logs.rs
>      }
this can be removed once I've merged this:

https://github.com/alloy-rs/alloy/pull/101

2024-01-10 14:23 UTC, mattsse requested changes
this lgtm

pending Default usage and sanity check @DaniPopes

2024-01-10 14:23 UTC, mattsse commented on crates/evm/evm/src/inspectors/logs.rs
>      }
this can now be replace with the Default impl

2024-01-10 14:31 UTC, DaniPopes commented
Needs rebase to alloy-primitives 0.6.0. `Log` is now `LogData` among other things.

2024-01-11 03:17 UTC, qiweiii commented
Does this mean I need to update `alloy_rpc_types::Log` to `use alloy_primitives::Log`

2024-01-11 03:29 UTC, DaniPopes commented
Yes that would be ideal, since the only fields we're using are data and topics

2024-01-11 07:58 UTC, mattsse commented
that sounds reasonable!

2024-01-11 14:58 UTC, mattsse approved these changes
lgtm,
pending @DaniPopes

2024-01-11 15:02 UTC, DaniPopes approved these changes

2024-01-11 15:09 UTC, merged