added arg and computing state in function of some overrides
foundry-rs/foundry pull request #6985
Opened 2024-02-01 15:16 UTC by loocapro

## Motivation
Related to #6980

## Solution
Added overrides arg and taking into account when computing the call.

2024-02-01 19:39 UTC, mattsse requested changes
pedantic style nit

2024-02-01 19:39 UTC, mattsse commented on crates/anvil/src/eth/api.rs
> +                        state::apply_state_override(overrides.into_iter().collect(), state)?;
this can be simplified with an if let Some instead

2024-02-01 19:39 UTC, mattsse commented on crates/anvil/src/eth/api.rs
> +                        ));
this might be possible with future api, but for now this is ok

2024-02-02 10:16 UTC, loocapro commented on crates/anvil/tests/it/transaction.rs
> +    let recipient_address_formatted =
Is there a better way to go from H160 to Alloy::Address? @mattsse

2024-02-02 16:39 UTC, mattsse approved these changes
nice!

2024-02-02 18:06 UTC, merged