fix issue #971
foundry-rs/foundry pull request #7101
Opened 2024-02-13 09:37 UTC by malik672

<!--
Fixed isse #971 

Added more positive fuzz tests

2024-02-13 14:23 UTC, mattsse approved these changes

2024-02-13 14:24 UTC, mattsse reviewed
I think this interferes with an existing test

2024-02-14 15:47 UTC, malik672 commented
> I think this interferes with an existing test

what do you think I should do

2024-02-14 15:47 UTC, malik672 commented
rewrite the tests?

2024-02-14 15:47 UTC, malik672 commented
i think i will run the ci on my computer, as I'm building

2024-02-20 05:55 UTC, malik672 commented
do you think the failure here might be to race conditons

2024-02-20 14:22 UTC, mattsse requested changes
the issue here is that these functions are being run in another test:

--- TRY 3 STDERR:        forge::it fuzz::test_fuzz ---
thread 'fuzz::test_fuzz' panicked at crates\forge\tests\it\fuzz.rs:37:22:
Test testSuccessChecker(uint256) did not fail as expected.
Reason: None
Logs:

best solution here would be to move the new tests to a new contract/file

2024-02-22 14:23 UTC, malik672 commented
ok

2024-02-22 15:15 UTC, onbjerg reviewed
small nits

2024-02-22 15:15 UTC, onbjerg commented on testdata/trace/Trace.t.sol
> +    event ChildDepth(uint256 childDepth);
```suggestion
    event ChildDepth(uint256 childDepth);
```

2024-02-22 15:15 UTC, onbjerg commented on testdata/cheats/ReadCallers.t.sol
> +
```suggestion

```

2024-02-22 15:15 UTC, onbjerg commented on testdata/cheats/Broadcast.t.sol
> +        vm.startBroadcast(ACCOUNT_A);
```suggestion
        vm.startBroadcast(ACCOUNT_A);
```

2024-02-23 07:15 UTC, malik672 commented
I think I've fixed it

2024-02-26 14:09 UTC, onbjerg requested changes

2024-02-26 14:09 UTC, onbjerg commented on crates/forge/tests/it/fuzz.rs
> +                "testSuccessChecker1(uint256)" |
```suggestion
                "testSuccessChecker(uint256)" |
```

2024-02-26 16:45 UTC, malik672 reviewed
done

2024-02-27 14:38 UTC, onbjerg approved these changes
thanks!

2024-02-27 14:50 UTC, merged