issue 6319: copy raw sliced value as tail in new value to be converted
foundry-rs/foundry pull request #7194
Opened 2024-02-20 19:18 UTC by grandizzy

## Motivation
additional fix for #6319 
tested with https://github.com/foundry-rs/foundry/issues/6319#issuecomment-1902693003 not sure though how to add a unit test for it, please advise

## Solution
- the sliced storage value should be used as tail when returning the value of the storage slot.

2024-02-20 20:11 UTC, mattsse requested changes
this looks correct to me,

can we convert the commend referenced in the issue into a `casttest!` ?

2024-02-20 20:17 UTC, mattsse commented
can use this one JQNGFHINKS1W7Y5FRXU4SPBYF43J3NYK46

2024-02-21 05:53 UTC, grandizzy commented
> can use this one JQNGFHINKS1W7Y5FRXU4SPBYF43J3NYK46

great, added with https://github.com/foundry-rs/foundry/pull/7194/commits/649f5d961ac2387801dd49340e354f27ff60b4ab

2024-02-21 10:37 UTC, mattsse approved these changes

2024-02-21 10:37 UTC, merged