feat: don't request Solc JSON AST unless absolutely necessary
foundry-rs/foundry pull request #7197
Opened 2024-02-20 22:27 UTC by DaniPopes

The Solc JSON AST output is very expensive to both serialize on the compiler's side, and deserialize on our side due to its very nested nature and generally big size.

I believe we currently use this output only in `coverage` and `flatten`.

---

Note that I'm using debug profile with hyperfine so it will be even faster.

Default `forge init` project:
![image](https://github.com/foundry-rs/foundry/assets/57450786/795ca6d5-d85a-4d83-bc39-432ff33a61ac)

Solmate:
![image](https://github.com/foundry-rs/foundry/assets/57450786/ff800079-50cb-47e1-9e11-29f4a5494845)

2024-02-20 23:10 UTC, mattsse reviewed
does this affect the regular forge build artifacts? 

~~we added metadata because this is apparently used by some tools~~

that's not part of metadata, so I think we can do that, but not entirely sure

2024-02-21 00:30 UTC, mattsse reviewed
I'd be fine with that.

we should check with slither first if they're relying on this in the artifacts file

2024-02-21 00:30 UTC, onbjerg requested changes
some external tools rely on this, so i'd add a flag to `forge build` to get this back

2024-02-21 00:41 UTC, mds1 commented
cc @0xalpharush for thoughts on how this affects slither

2024-02-21 00:51 UTC, gakonst commented
Can we get a comparison for release mode compilation time improvements due to this on a large repo? e.g. Optimism contracts

2024-02-21 01:07 UTC, onbjerg approved these changes

2024-02-21 01:07 UTC, onbjerg commented on crates/forge/bin/cmd/coverage.rs
> +            "https://github.com/foundry-rs/foundry/issues/3357\n"
formatting lookig funky here

2024-02-21 01:48 UTC, DaniPopes commented
> Can we get a comparison for release mode compilation time improvements due to this on a large repo? e.g. Optimism contracts

@gakonst
The overwhelming majority of the time is spent in solc so `release` mode on our side won't do much here.

It's 2-3% faster on clean builds, up to 5-10x for sablier/v2-core (absolute time save of about 2.5s for both). Note that time saved is proportional to amount of total artifacts.

2024-02-21 03:24 UTC, 0xalpharush commented
I ran `foundryup -b dani/drop-ast` and it does make slither not work since the ASTs are missing. I think it is fine to drop from `forge build` but I'd prefer `forge build --build-info` (the hardhat artifact style) to be backwards compatible ofc. Otherwise, we'd have to cut a release and handle the case where people are not on this version of foundry yet

2024-02-24 03:06 UTC, merged