[cast] Fix cast wallet verify
foundry-rs/foundry pull request #7215
Opened 2024-02-22 22:05 UTC by mdehoog

## Motivation

#7088 broke `cast wallet verify`. The following worked previously and no longer works:
```
cast wallet verify --address 0x28A4F420a619974a2393365BCe5a7b560078Cc13 hello $(cast wallet sign --private-key 0x678d52cc9fdedbf5be1cd9b479725aab5ed8b9fbfbfeff9b660dff8b5766bf2a hello)
```

Error:
```
Odd number of digits
```

## Solution

This PR reverts a subset of the PR above which fixes the issue. Happy to take suggestions on alternative paths. Thanks!

2024-02-22 22:11 UTC, stevieraykatz commented
This addresses https://github.com/foundry-rs/foundry/issues/7214

2024-02-22 23:45 UTC, Evalir requested changes
Thanks! Indeed, this is a fix, but not the one we want—we want to keep the old types and not import any additional ethers types.

The fix would be to switch to using `recover_address_from_msg` instead of `recover_address_from_prehash`.

2024-02-22 23:45 UTC, Evalir commented on crates/cast/bin/cmd/wallet/mod.rs
> +                match signature.verify(Self::hex_str_to_bytes(&message)?, address.to_ethers()) {
We should not be using the old ethers type here. We should actually use `recover_address_from_msg` from the alloy `Signature` type.

2024-02-22 23:47 UTC, Evalir approved these changes
I've added a commit that applies the fix described—thanks!

2024-02-22 23:56 UTC, DaniPopes requested changes
Can you please add a test

2024-02-23 00:20 UTC, DaniPopes approved these changes

2024-02-23 00:30 UTC, merged