Added --only-src to generate bindings for only `src/`
foundry-rs/foundry pull request #7266
Opened 2024-02-28 18:13 UTC by lakshya-sky

Should fix https://github.com/foundry-rs/foundry/issues/4375

2024-02-28 18:41 UTC, mattsse requested changes

2024-02-28 19:37 UTC, tynes commented on crates/forge/bin/cmd/bind.rs
> +                        if contract_path.starts_with("src/") {
Shouldn't this be pulled from the config as the name of this directory can be configured?

2024-06-28 15:54 UTC, zerosnacks commented
Hi @lakshya-sky thanks for your PR!

We've recently moved `forge bind` to Alloy, would be great to get your PR merged

Would you be able to update your PR to resolve the merge conflict?

2024-06-28 15:57 UTC, lakshya-sky commented
cool! I can change it this weekend or probably early next week.

2024-07-10 01:34 UTC, closed without merging