feat(anvil): configure slots_in_an_epoch
foundry-rs/foundry pull request #7335
Opened 2024-03-07 19:19 UTC by yash-atreya

## Motivation
Addresses #7245 

Ref: https://github.com/foundry-rs/foundry/issues/7245#issuecomment-1978532399

## Solution

Added `--slots-in-an-epoch` arg to anvil cli. Default is `32`.

2024-03-07 20:37 UTC, DaniPopes requested changes

2024-03-07 20:37 UTC, DaniPopes commented on crates/anvil/src/config.rs
> +            if let Some(slots_in_an_epoch) = slots_in_an_epoch { slots_in_an_epoch } else { 32 };
```suggestion
            slots_in_an_epoch.unwrap_or(32)
```

2024-03-07 20:37 UTC, DaniPopes commented on crates/anvil/src/eth/backend/mem/mod.rs
> +                        .saturating_sub(U64::from(self.slots_in_an_epoch) * U64::from(2))
we can remove all the U64 usage here and just use primitive u64

2024-03-07 21:48 UTC, mattsse requested changes
smol nits

2024-03-07 21:48 UTC, mattsse commented on crates/anvil/src/config.rs
> +    pub fn with_slots_in_an_epoch(mut self, slots_in_an_epoch: Option<u64>) -> Self {
```suggestion
    pub fn with_slots_in_an_epoch(mut self, slots_in_an_epoch: u64) -> Self {
```

2024-03-07 21:48 UTC, mattsse commented on crates/anvil/src/cmd.rs
> +    pub slots_in_an_epoch: Option<u64>,
```suggestion
    pub slots_in_an_epoch: u64,
```

2024-03-07 21:48 UTC, mattsse commented on crates/anvil/src/cmd.rs
> +    #[arg(long, value_name = "SLOTS_IN_AN_EPOCH", default_value = "32")]
```suggestion
    #[arg(long, value_name = "SLOTS_IN_AN_EPOCH", default_value_t = 32)]
```

2024-03-07 22:49 UTC, DaniPopes approved these changes

2024-03-08 13:36 UTC, mattsse approved these changes

2024-03-08 13:36 UTC, merged