[wip] chore: refactor tests layout
foundry-rs/foundry pull request #7410
Opened 2024-03-15 15:08 UTC by klkvr

## Motivation

Refactors tesdata durectory to separate `default` tests from `cancun` and potentially more directories.

## Solution

Introduces `ForgeTestProfile` which manages configuration and layout of the test project.

2024-03-17 10:00 UTC, mattsse requested changes
awesome,

I believe this is exactly what we need, and unlocks the blobfee/cancun related cheatcodes

mind taking a look at this @onbjerg ?

2024-03-18 00:10 UTC, onbjerg approved these changes
i think this should work

2024-03-18 12:08 UTC, mattsse approved these changes
lgtm

2024-03-18 14:21 UTC, DaniPopes requested changes

2024-03-18 14:21 UTC, DaniPopes commented on crates/forge/tests/it/config.rs
> +pub async fn forked_runner(test_data: &ForgeTestData, rpc: &str) -> MultiContractRunner {
Can we make these methods on `ForgeTestData`?

2024-03-20 00:47 UTC, DaniPopes approved these changes

2024-03-20 02:45 UTC, merged