feat: print IPC path
foundry-rs/foundry pull request #7526
Opened 2024-03-30 15:21 UTC by kamuik16

## Motivation

Closes #7525

2024-03-30 21:17 UTC, Evalir requested changes

2024-03-30 21:17 UTC, Evalir commented on crates/anvil/src/lib.rs
> +        if let Some(ipc_path) = self.ipc_path() {
looks good! let's move this into the `if !self.config.silent` check above so it respects it

2024-03-31 05:28 UTC, Evalir approved these changes

2024-04-01 13:03 UTC, mattsse requested changes
I want this printed above the regular "Listening on:" out put, so ipc first then listening on

2024-04-01 13:29 UTC, kamuik16 commented
> I want this printed above the regular "Listening on:" out put, so ipc first then listening on

done!

2024-04-01 13:30 UTC, mattsse approved these changes

2024-04-01 16:42 UTC, merged