feat(verify): multichain verification for etherscan
foundry-rs/foundry pull request #7537
Opened 2024-04-01 16:55 UTC by yash-atreya

## Motivation

Closes #7485 

## Solution

Incorporate the `chain_id` parameter while building etherscan client

2024-04-01 16:57 UTC, mattsse approved these changes
lgtm!

2024-04-01 18:06 UTC, yash-atreya commented
@mattsse Failing cargo deny due to open-ssl being banned. This occurs after updating to `reqwest@0.12.2` and enabling the `default-tls` feature on it to use it here: 

https://github.com/yash-atreya/foundry/blob/f686351921f0d666fa726b8420aa27d312c0e0d8/crates/config/src/etherscan.rs#L323

2024-04-01 18:40 UTC, mattsse requested changes
no openssl

2024-04-01 18:40 UTC, mattsse commented on crates/config/Cargo.toml
> +    "default-tls",
we don't want this,
why is this enabled?

2024-04-01 19:33 UTC, mattsse commented on crates/config/Cargo.toml
> +    "default-tls",
this should be there with any tls feature, 
ref:

https://github.com/foundry-rs/foundry/blob/a16714ed40f733013d7a80f4f969564175c3318e/crates/forge/Cargo.toml#L107-L113

2024-04-02 17:23 UTC, mattsse approved these changes

2024-04-02 17:23 UTC, merged