Make batch size as a option
foundry-rs/foundry pull request #7540
Opened 2024-04-02 06:41 UTC by hoaleee

Make batch size as a option.

## Motivation

We are developing a network based on zkevm - a new evm platform. We are trying to increase compatibility of MUD Framework and zkevm. We found that with the default batch size of 100, zkevm may not be able to handle it, with the --slow option the waiting time is too long. 

## Solution

So we added batch size as an option to increase customization compatibility with many chains.

2024-04-04 16:16 UTC, DaniPopes requested changes
cc @klkvr

2024-04-04 16:16 UTC, DaniPopes commented on crates/script/src/broadcast.rs
> +                let valid_batch_size = if self.args.batch_size > 100 { 100 } else { self.args.batch_size };
```suggestion
                let valid_batch_size = self.args.batch_size.min(100);
```

2024-04-04 16:16 UTC, DaniPopes commented on crates/script/src/lib.rs
> +
```suggestion
```

2024-04-04 16:16 UTC, DaniPopes commented on crates/script/src/lib.rs
> +    /// --batch-size
```suggestion
```

2024-04-04 16:16 UTC, DaniPopes commented on crates/script/src/lib.rs
> +    pub batch_size: i32,
```suggestion
    pub batch_size: usize,
```

2024-04-04 16:16 UTC, DaniPopes commented on crates/script/src/broadcast.rs
> +                let batch_size = if sequential_broadcast { 1 } else { valid_batch_size as usize };
```suggestion
                let batch_size = if sequential_broadcast { 1 } else { valid_batch_size };
```

2024-04-04 16:19 UTC, klkvr approved these changes

2024-04-06 15:18 UTC, DaniPopes approved these changes
Thanks!

2024-04-06 15:18 UTC, merged