chore(forge): kB to B in build --sizes
foundry-rs/foundry pull request #7588
Opened 2024-04-07 09:52 UTC by kamuik16

Closes #7567

2024-04-07 09:53 UTC, kamuik16 commented
Example Output:
```bash
Compiler run successful!
| Contract | Size (B) | Margin (B) |
|----------|----------|------------|
| Counter  | 247      | 24329      |
```

2024-04-08 04:08 UTC, onbjerg requested changes

2024-04-08 04:08 UTC, onbjerg commented on crates/common/src/compile.rs
> +                Cell::new(margin as f64).fg(color),
we can remove the `as f64` casts

2024-04-08 08:38 UTC, Evalir approved these changes
lgtm

2024-04-08 10:10 UTC, DaniPopes approved these changes
Thanks!

2024-04-08 10:10 UTC, merged