feat(forge): blobbasefee cheatcode
foundry-rs/foundry pull request #7598
Opened 2024-04-08 13:25 UTC by kamuik16

Closes #7002

2024-04-08 13:34 UTC, Evalir requested changes
needs forge fmt + nit. This needs to be run using the cancun test profile

2024-04-08 13:34 UTC, Evalir commented on crates/cheatcodes/spec/src/vm.rs
> +    /// and as a result will get optimized out by the compiler.
let's also add the issue link here

2024-04-08 13:36 UTC, kamuik16 commented on crates/cheatcodes/spec/src/vm.rs
> +    /// and as a result will get optimized out by the compiler.
> let's also add the issue link here

which issue should I link here?

2024-04-08 13:39 UTC, kamuik16 commented
> Thanks! needs forge fmt + nit. tests need to be run using the cancun test profile

ran the test with cancun evm version but did not push into the pr.

2024-04-09 17:15 UTC, yash-atreya commented
Hey @kamuik16, let me know if you need help with anything

2024-04-09 17:16 UTC, kamuik16 commented
> Hey @kamuik16, let me know if you need help with anything

I am waiting for reviews. I think it's done from my side. Working correctly.

2024-04-09 17:33 UTC, mattsse approved these changes
lgtm

2024-04-09 17:33 UTC, yash-atreya commented
> > Hey @kamuik16, let me know if you need help with anything
> 
> I am waiting for reviews. I think it's done from my side. Working correctly.
CI tests are failing

2024-04-09 17:36 UTC, mattsse requested changes
ah this is now a cheat that only works with CANCUN, hence the failing test.

so what we need now is a test, just like:

https://github.com/foundry-rs/foundry/blob/master/crates/forge/tests/it/cheats.rs#L10-L26

but uses 

https://github.com/foundry-rs/foundry/blob/master/crates/forge/tests/it/test_helpers.rs#L273-L275

and we need a cancun/cheats folder not default/cheats

## TODO
* create cancun/cheats folder and move test
* add a new rust test similar to cheats that uses the `TEST_DATA_CANCUN` config

2024-04-09 17:39 UTC, kamuik16 commented
i will implement this by tomorrow, sounds good?

> ah this is now a cheat that only works with CANCUN, hence the failing test.
> 
> so what we need now is a test, just like:
> 
> https://github.com/foundry-rs/foundry/blob/master/crates/forge/tests/it/cheats.rs#L10-L26
> 
> but uses
> 
> https://github.com/foundry-rs/foundry/blob/master/crates/forge/tests/it/test_helpers.rs#L273-L275
> 
> and we need a cancun/cheats folder not default/cheats
> 
> ## TODO
> * create cancun/cheats folder and move test
> * add a new rust test similar to cheats that uses the `TEST_DATA_CANCUN` config

i'll try and get it done by tomorrow eod, sounds good?

2024-04-10 09:25 UTC, kamuik16 commented
hey @mattsse! I moved the test into cancun folder and ci is passing but struggling with the test.

2024-04-10 10:58 UTC, mattsse requested changes
lgtm

2024-04-10 10:58 UTC, mattsse approved these changes

2024-04-10 11:10 UTC, merged

2024-04-10 11:20 UTC, kamuik16 commented
> lgtm

thanks for the test help!