fix: Type parameter of Vm.prevrandao as uint256
foundry-rs/foundry pull request #7695
Opened 2024-04-17 06:24 UTC by qiweiii

## Motivation

fix: #7693

## Solution

change Vm.prevrandao type

2024-04-17 06:24 UTC, qiweiii commented
Are these changes enough?

2024-04-17 09:46 UTC, mattsse requested changes

2024-04-17 09:46 UTC, mattsse commented on crates/cheatcodes/spec/src/vm.rs
> +    function prevrandao(uint256 newPrevrandao) external;
this replaces the function, we should overload it instead so this becomes non breaking

2024-04-19 09:43 UTC, mattsse approved these changes
lgtm, mind upstreaming this to forge-std as well?

2024-04-19 09:43 UTC, merged