Port Anvil tests to Alloy
foundry-rs/foundry pull request #7701
Opened 2024-04-18 10:17 UTC by zerosnacks

## Motivation

Includes #7619 

## Solution

2024-04-22 07:43 UTC, zerosnacks commented
From @yash-atreya 

- `ethers` has been removed from all anvil tests except `optimism` tests (@zerosnacks is on it).

- Few tests have been migrated but fail due to issues:

1. https://github.com/alloy-rs/alloy/issues/389 
Tests failing due to `test_fork_snapshotting_blocks`,  `test_fork_timestamp`, `test_fork_reset_moonbeam`, `can_call_ots_get_transaction_error`, `can_replace_transaction`.

2. RpcError in `watch_full_pending_transactions`
```bash
ErrorPayload { code: -32602, message: "invalid type: boolean `true`, expected
// unit", data: None } originating from watch_full_pending_transactions
```
Test failing: `can_stream_pending_transactions`

3. Pubsub `channel_size` issue in `test_sub_new_heads_fast`.

Once, `optimism` tests have been migrated, we should proceed to remove `ethers` completely from the codebase by tackling the following in no particular order: 

1. Migrate `cast bind` and `forge bind`
2. Doc tests in `cast/lib.rs`
3. Remove `ethers` provider from `foundry_common`. This can be done as soon as `optimisim` is migrated.
4. `RuntimeClient` in `foundry_common`
5. `RuntimeTransport` in `foundry_common`
6. forge cli tests 
7. Finally remove the types `ToAlloy` and `ToEthers` from `foundry_common`

2024-04-25 09:06 UTC, zerosnacks commented
@yash-atreya I've marked this as ready for review now that all tests are running. I think it is best if the final migration of `cast bind` and `forge bind` is handled in a standalone ticket given its possible complexity and the diff is already massive.

2024-04-25 13:07 UTC, mattsse requested changes
nice,

a few more nits and suggestions

let's convert all for those

```rust
http_provider(&handle.http_endpoint());
```

to `handle.http_provider()`

same for ws and ipc

2024-04-25 13:07 UTC, mattsse commented on crates/anvil/tests/it/pubsub.rs
> +        };
nit: the async scope is not needed here and can just be extracted and put after the mine.await

2024-04-25 13:07 UTC, mattsse commented on crates/anvil/tests/it/transaction.rs
> +#[ignore]
this shoudl not be ignored

2024-04-25 13:07 UTC, mattsse commented on crates/common/src/provider/mod.rs
> +pub type RpcUrl = String;
this alias is not useful

2024-04-25 13:07 UTC, mattsse commented on crates/common/src/provider/mod.rs
> +                            Url::parse(&format!("file://{}", path.display()))
this could be an issue for the windows ipc

2024-04-25 14:56 UTC, zerosnacks commented on crates/anvil/tests/it/anvil_api.rs
> +// async fn can_remove_pool_transactions() {
good catch, was previously blocked by missing txpool methods - now fixed

2024-04-25 16:25 UTC, zerosnacks commented on crates/anvil/tests/it/ipc.rs
> +// the file specified." }))` on Windows
Got this error:

Transport(Custom(TransportErrorTest(Transport(Custom(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })), "file:///pipe/anvil-ipc-7861286456766970431", "\\\\.\\pipe\\anvil-ipc-7861286456766970431")))

The conversion appears to be correct (format: error, url, path), expected format is: `\\.\pipe\reth_engine_api.ipc` after escaping.

Attempted to replace it with the approach defined in this test in Alloy by using a tempfile: https://github.com/alloy-rs/alloy/blob/4d77029ba61284a6b4185f46581b4d9bce34f5fd/crates/rpc-client/tests/it/ipc.rs#L5

I noticed that Alloy currently only tests on latest Ubuntu making it likely that this is an area of the codebase not fully tested yet.

Going to hop onto my Windows machine and see if I can debug it there.

2024-04-26 13:57 UTC, mattsse approved these changes
I'm okay with disabling ipc tests on windows for now, and fix separately on alloy or in a follow up once we found it

but i really want more context (the path) included in this error, because this is useless:

> thread 'ipc::can_get_block_number_ipc' panicked at crates\anvil\tests\it\ipc.rs:31:49:
called `Result::unwrap()` on an `Err` value: Transport(Custom(TransportError(Transport(Custom(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })))))

this needs to happen in alloy though

2024-04-26 16:00 UTC, zerosnacks commented
> I'm okay with disabling ipc tests on windows for now, and fix separately on alloy or in a follow up once we found it
> 
> but i really want more context (the path) included in this error, because this is useless:
> 
> > thread 'ipc::can_get_block_number_ipc' panicked at crates\anvil\tests\it\ipc.rs:31:49:
> > called `Result::unwrap()` on an `Err` value: Transport(Custom(TransportError(Transport(Custom(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })))))
> 
> this needs to happen in alloy though, do we know where this is thrown?

I agree, lets not make this a blocker and handle this in a follow up.

I've added some extra information to the `TransportError` in Foundry.

Some places I found suspicious:

casting to `ok()`

https://github.com/foundry-rs/foundry/blob/d21c3e7e1864d909cbece8ad650f91770193f128/crates/anvil/src/lib.rs#L324

Tests for the existence of the file, not something we do in the current test. However when I changed it to use Alloy's `NamedTempFile` of the example it didn't work.

https://github.com/alloy-rs/alloy/blob/bbef8de3fd203bf6feb26dc619f42b2bb2ecd4e3/crates/rpc-client/src/builtin.rs#L147-L162

And as previously highlighted

https://github.com/foundry-rs/foundry/blob/5f801b490d776e4f0e51a11c4d91de2c30e3ad3c/crates/common/src/provider/mod.rs#L113-L117

2024-04-26 16:18 UTC, mattsse approved these changes
gg

let's add a windows target to alloy CI and ensure IPC works cross platform

2024-04-26 16:25 UTC, DaniPopes approved these changes

2024-04-26 16:53 UTC, zerosnacks commented
> gg
> 
> let's add a windows target to alloy CI and ensure IPC works cross platform

Opened a draft PR here: https://github.com/alloy-rs/alloy/pull/642

I previously made a mistake when I was testing it earlier against the CI (mistakingly had set `runs-on` to `ubuntu-latest`, not `{{ matrix.os }}`). The PR handles this correctly now and shows build failures / test failures for various reasons which I'll address in that PR.

2024-04-26 17:03 UTC, klkvr approved these changes

2024-04-26 17:04 UTC, merged