migrate: cast doctests to alloy
foundry-rs/foundry pull request #7768
Opened 2024-04-23 18:32 UTC by yash-atreya

## Motivation

Remove `ethers` from codebase

## Solution

Migrate to `alloy`

2024-04-23 20:38 UTC, onbjerg approved these changes
smol nits lgtm otherwise

2024-04-23 20:38 UTC, onbjerg commented on crates/cast/src/lib.rs
> +    /// function greeting(uint256 i) public returns (string);
```suggestion
    ///     function greeting(uint256 i) public returns (string);
```
nit

2024-04-23 20:38 UTC, onbjerg commented on crates/cast/src/lib.rs
> +    /// function greeting(uint256 i) public returns (string);
```suggestion
    ///     function greeting(uint256 i) public returns (string);
```
nit

2024-04-23 20:38 UTC, onbjerg commented on crates/cast/src/lib.rs
> +    /// function greet(string greeting) public;
```suggestion
    ///     function greeting(uint256 i) public returns (string);
```
nit

2024-04-23 20:44 UTC, mattsse requested changes

2024-04-23 20:44 UTC, mattsse commented on crates/cast/src/lib.rs
> +    /// let provider = get_http_provider("http://localhost:8545");
this should not be part of the docs, this is an internal helper function

the example should just use a regular alloy provider

2024-04-23 20:44 UTC, mattsse commented on crates/cast/src/lib.rs
> +    /// let provider = get_http_provider("http://localhost:8545");
same

2024-04-23 22:54 UTC, DaniPopes approved these changes

2024-04-23 22:56 UTC, merged

2024-04-27 12:47 UTC, ArkFunds approved these changes
True

2024-04-27 12:47 UTC, ArkFunds approved these changes
TRUE