Bump alloy to use `get_receipt` hotfix
foundry-rs/foundry pull request #7772
Opened 2024-04-24 20:14 UTC by yash-atreya

## Motivation

Use `get_receipt` hotfix from updated alloy version.

## Solution

Bump

2024-04-24 20:42 UTC, mattsse reviewed
there's likely something wrong with script or the send logic of alloy

2024-04-25 00:04 UTC, DaniPopes approved these changes

2024-04-25 00:05 UTC, merged

2024-04-25 00:08 UTC, mattsse requested changes
few pedantic nits, can be done in a followup

2024-04-25 00:08 UTC, mattsse commented on crates/cast/bin/cmd/call.rs
> +        req.set_input::<Bytes>(data.into());
I don't think the type hint is required
```suggestion
        req.set_input(data);
```

2024-04-25 00:08 UTC, mattsse commented on crates/cast/bin/cmd/estimate.rs
> +        req.set_input::<Bytes>(data.into());
same

2024-04-25 00:08 UTC, mattsse commented on crates/cast/bin/tx.rs
> +    // TODO: Possible bug here?
I think this is correct
```suggestion
```

2024-04-25 01:10 UTC, yash-atreya commented
Suggestions addressed in #7701

2026-06-19 09:19 UTC, Alexis98MG approved these changes