feat: forge decode-error
foundry-rs/foundry pull request #7775
Opened 2024-04-24 23:08 UTC by nhtyy

## Motivation

When debugging eth integrations across platforms sometimes the only thing you can work with is the revert data, this can turn into searching thru forge inspect or manually checking if its an error that can be decoded as a string

## Solution

Introduce `forge decode-error`, which searches the project (if any) and checks against revert/panic types.

2024-04-29 02:34 UTC, tynes commented
This seems like it would be better as a `cast` command

2024-04-29 09:52 UTC, onbjerg requested changes
Please move this to cast if there isn't already a command that does this (e.g. cast abi-decode)

2024-07-31 12:16 UTC, zerosnacks commented
Hi @nhtyy thanks for your PR! I can see how this feature could be useful. Would you be interested in porting your changes to `cast` as `cast decode-error`?

2024-08-12 10:30 UTC, nhtyy commented
Hey @zerosnacks. 

Apologies for the delay but will give this a shot in the next week or two

2024-08-19 01:08 UTC, nhtyy commented
@zerosnacks 

Im going to work on this during this upcoming week, just wanted your opinion because `cast` doesn't have any "project awareness" in the since that it doesn't ever look for a foundry.toml

my thinking is either if were in a foundry project we search there, or if not we search the `.foundry` cache?

do you think either of these approaches is ok?

2025-04-29 22:09 UTC, DaniPopes commented
Superseded by https://github.com/foundry-rs/foundry/pull/9428.

2025-04-29 22:09 UTC, closed without merging