chore: stop using RuntimeOrHandle
foundry-rs/foundry pull request #7860
Opened 2024-05-05 12:08 UTC by DaniPopes

Not necessary, we're always in a tokio runtime

2024-05-05 12:51 UTC, DaniPopes commented
Ah this is not the case in tests because of rayon.. @mattsse wat do

2024-05-05 13:05 UTC, mattsse requested changes
I think we can still use RuntimeOrHandle::new() in the new block_on fn

or rather modify:

```rust
 match Handle::try_current() {
                    Ok(handle) => RuntimeOrHandle::Handle(handle),
                    Err(_) => RuntimeOrHandle::Runtime(Runtime::new().expect("Failed to start runtime")),
                }
```

so that the error case creates a new runtime with the current thread?

2024-05-06 20:35 UTC, DaniPopes commented
I would rather just not spawn a runtime per `vm.rpc` call, that is just wrong. We can pass around `Handle`s and enter them to have the tokio runtime available in rayon threads.

2024-05-06 21:05 UTC, mattsse approved these changes

2024-05-06 21:17 UTC, merged