feat(forge) - add test progress
foundry-rs/foundry pull request #7914
Opened 2024-05-13 09:24 UTC by grandizzy

## Motivation
Closes #585 

## Solution
- make sue of `indicatif` crate
- add `--show-progress` arg  (to give more time for feedback / OS tests, then make it default and add a `--stream-results` flag for legacy output)
- long running tasks gets their own entry / progress bar in test suite progress (rn only for invariants but can be extended to regular fuzz tests too). Invariants show [current run / total runs] and then number of calls to shrink (if case)
- when a test suite is finished it is moved from running tasks to summary section showing the result summary
- when all test suits are completed then detailed results are streamed

![test-out](https://github.com/foundry-rs/foundry/assets/38490174/4ce79668-b31c-465a-a19c-af5abc367110)

TBD: rn the fail fast flag doesn't stop test case execution (rayon par iter continue to run until all tasks are completed), need to find a way to exit early when such

2024-05-13 15:09 UTC, mattsse commented
> rn the fail fast flag doesn't stop test case execution (rayon par iter continue to run until all tasks are completed), need to find a way to exit early when such

I think we could add a termination check with something like an `Arc<AtomicBool>` to exit early

2024-05-15 06:22 UTC, mattsse reviewed
@DaniPopes should be proceed with this given that this is opt in for now and do a larger cleanup for the nested suite par_iter and exit early separately or do this here?

2024-05-22 15:57 UTC, DaniPopes requested changes

2024-06-05 10:14 UTC, grandizzy commented on crates/cli/src/utils/cmd.rs
> +macro_rules! init_tests_progress {
I removed those macros and moved logic in structs within newly `progress` mod, pls check https://github.com/foundry-rs/foundry/pull/7914/commits/7aaafc8e20d15e1cb6621483f104906bb9d547d3

2024-06-06 17:52 UTC, grandizzy commented
@DaniPopes please take a look when you have time, would love to get this merged and take feedback from community. Thank you 🙏

2024-06-07 13:28 UTC, DaniPopes approved these changes

2024-06-07 13:29 UTC, DaniPopes commented
needs rebase + clippy

2024-06-07 14:07 UTC, merged