refactor: clean-up cast send
foundry-rs/foundry pull request #7967
Opened 2024-05-21 18:08 UTC by klkvr

## Motivation

Refactor `build_tx` used in cast send and cast mktx

ref #7965
closes https://github.com/foundry-rs/foundry/issues/7959

## Solution

Implement `CastTxBuilder` as a replacement for `build_tx`.

It is implemented as a stateful builder because we require `tx_kind` to be known before resolving calldata.

2024-05-21 18:48 UTC, onbjerg commented on crates/cast/bin/cmd/send.rs
> -            }
default behavior is next nonce, resend is overriding an existing tx in the mempool

2024-05-21 22:15 UTC, klkvr commented on crates/cast/bin/cmd/send.rs
> -            }
> i think this is just a sanity check as technically a node could also do highest_nonce_in_mempool + 1 for the next tx. i'd add it back

hmm, sorry what do you mean here? it seems that currently this flag has no effect, perhaps it should be changed somehow?

2024-05-23 13:50 UTC, mattsse requested changes
this is a great improvement,

I'd like to see a few more docs on the functions and types, ideally with derive debug if possible

2024-05-23 13:50 UTC, mattsse commented on crates/cast/bin/cmd/send.rs
> -            }
this is the default get tx count behaviour which also checks the pool so this check is indeed redundant

2024-05-23 15:53 UTC, klkvr commented
Added more docs and also cleaned up estimate, call and access-list commands to have similar flow and use `CastTxBuilder` as well

2024-05-23 17:06 UTC, DaniPopes approved these changes

2024-05-23 17:06 UTC, DaniPopes commented on crates/cast/bin/cmd/access_list.rs
> +    utils::{self},
```suggestion
    utils,
```

2024-05-23 17:06 UTC, DaniPopes commented on crates/cast/bin/cmd/access_list.rs
```suggestion
```

2024-05-23 17:06 UTC, DaniPopes commented on crates/cast/bin/cmd/call.rs
```suggestion
```

2024-05-23 17:06 UTC, DaniPopes commented on crates/cast/bin/cmd/call.rs
> +            mut tx,
could [to, sig, args, data] go into tx?

2024-05-23 17:06 UTC, DaniPopes commented on crates/cast/bin/cmd/estimate.rs
```suggestion
```

2024-05-24 17:07 UTC, DaniPopes commented
Does this close https://github.com/foundry-rs/foundry/issues/7959?

2024-05-25 08:42 UTC, mattsse commented
yep

2024-05-25 08:42 UTC, mattsse approved these changes

2024-05-25 08:43 UTC, merged