feat(anvil): support millisecond mining with correct block.timestamp
foundry-rs/foundry pull request #8010
Opened 2024-05-29 13:03 UTC by yash-atreya

## Motivation

Fixes #7931 
Closes https://github.com/foundry-rs/foundry/issues/9142

## Solution

Adds `wall_clock_timestamp` in `TimeManager` with millisecond precision. 
This `wall_clock_timestamp` is then used as a reference in interval mining to update the `next_timestamp`. 

Moreover, we now interpret `TimeManager.interval` as milliseconds instead of seconds. This brings breaking changes to the following anvil API method: `evm_set_block_timestamp_interval`.

Note: We still interpret `--block-time` from CLI as seconds. Hence, for millisecond mining user sets the `--block-time` as `0.05` or `0.75` etc.

2024-05-29 13:03 UTC, yash-atreya commented
Need to add tests. DO NOT MERGE

2024-05-31 13:27 UTC, DaniPopes commented on testdata/lib/forge-std
rm

2024-05-31 13:27 UTC, DaniPopes commented on crates/anvil/src/eth/api.rs
> +    pub fn evm_set_block_timestamp_interval(&self, milliseconds: u64) -> Result<()> {
We can avoid a breaking change by making this f64 and do the same as CLI arg?

2024-06-03 09:42 UTC, yash-atreya commented
@mattsse ptal

2024-06-05 22:01 UTC, mattsse requested changes
hmm, this does not really address because this only changes the tracked timestamp value and has no effect on interval mining.

I think the right fix for this issue, which is much simpler would be here:

https://github.com/foundry-rs/foundry/blob/487892dd05730a4120b8ed2639b38d9c0bee5fe6/crates/anvil/src/eth/miner.rs#L157-L158

and we could leave the setblocktimestamp interval alone, we can't even express sub 1s intervals anyway.

2024-10-22 16:36 UTC, yash-atreya commented
Superseded by #9160. Turns out its a lot simpler than this approach.

2024-10-22 16:36 UTC, closed without merging