feat: add option to ignore directories from coverage report
foundry-rs/foundry pull request #8321
Opened 2024-07-01 12:01 UTC by zerosnacks

## Motivation

Follow-up of https://github.com/foundry-rs/foundry/pull/7301 as I'm not able to push directly to the fork

This PR includes the commits of https://github.com/dimazhornyk

Closes: #2988 

## Solution

Contrary to https://github.com/foundry-rs/foundry/pull/7301 I decided that for flexibility it is preferable to generalize beyond `glob` and instead use a `regex` on the filepath

- Fixes the formatting issues that slipped in 
- Fixes merge conflicts

2024-07-01 12:15 UTC, zerosnacks commented on crates/forge/bin/cmd/test/filter.rs
> +    pub coverage_pattern_inverse: Option<regex::Regex>,
I've opted for `no-match-coverage` to stay in line with the `no-match-*` pattern established (`no-match-test`, `no-match-contract`, `no-match-path`) 

See: https://github.com/foundry-rs/foundry/pull/7301#discussion_r1521015253

2024-07-01 12:38 UTC, mattsse requested changes

2024-07-01 12:38 UTC, mattsse commented on crates/evm/coverage/src/lib.rs
> +    pub fn filter_out_ignored_sources(&mut self, filter: &impl CoverageFilter) {
let's just replace this with an `Fn(&Path) -> bool`

2024-07-01 12:38 UTC, mattsse commented on crates/evm/coverage/src/lib.rs
> +        self.items = new_items;
isn't this just a `HashMap::retain`?

2024-07-01 18:30 UTC, mattsse approved these changes
lgtm 

pending @klkvr

2024-07-01 18:51 UTC, klkvr approved these changes
lgtm

2024-07-01 18:55 UTC, merged

2024-07-02 07:49 UTC, gosuto-inzasheru commented
thanks for this 🥇