Updated the soldeer version to 0.2.18 and added extra CLI tests
foundry-rs/foundry pull request #8441
Opened 2024-07-14 14:03 UTC by mario-eth

## Motivation

We added new functionality to Soldeer, using a git repo as a dependency.
https://github.com/mario-eth/soldeer/issues/48

This feature has been requested even tho I do not encourage abusing it but it can be used for various unpublished repos.

## Solution
Now we can use git to pull dependencies. It supports github and gitlab

Example:
```bash
forge soldeer install test-project~v1 git@github.com:test/test.git
forge soldeer install test-project~v1 git@gitlab.com:test/test.git
```

```bash
forge soldeer install test-project~v1 https://github.com/test/test.git
forge soldeer install test-project~v1 https://gitlab.com/test/test.git
```

Or using custom commit hashes
```bash
forge soldeer install test-project~v1 git@github.com:test/test.git 345e611cd84bfb4e62c583fa1886c1928bc1a464
```

2024-07-14 15:41 UTC, DaniPopes commented
Hey, this adds 3 C libraries as dependencies as you can see by the Cargo.lock diff. I would really prefer if this was not the case.

We dropped the git2 library a while ago in favor of just using the git CLI, see https://github.com/foundry-rs/foundry/blob/0e07ca51a2947f86d099645fb6eb6d0e47a4410d/crates/cli/src/utils/mod.rs#L276

In your case you can probably just get away with running `Command::new("git").args(["clone", a, b])`

2024-07-14 15:41 UTC, DaniPopes requested changes
Hey, this adds 3 C libraries as dependencies as you can see by the Cargo.lock diff. I would really prefer if this was not the case.

We dropped the git2 library a while ago in favor of just using the git CLI, see https://github.com/foundry-rs/foundry/blob/0e07ca51a2947f86d099645fb6eb6d0e47a4410d/crates/cli/src/utils/mod.rs#L276

In your case you can probably just get away with running `Command::new("git").args(["clone", a, b])`

2024-07-14 15:44 UTC, mario-eth commented
> Hey, this adds 3 C libraries as dependencies as you can see by the Cargo.lock diff. I would really prefer if this was not the case.
> 
> 
> 
> We dropped the git2 library a while ago in favor of just using the git CLI, see https://github.com/foundry-rs/foundry/blob/0e07ca51a2947f86d099645fb6eb6d0e47a4410d/crates/cli/src/utils/mod.rs#L276
> 
> 
> 
> In your case you can probably just get away with running `Command::new("git").args(["clone", a, b])`

Thanks for the suggestion. I am gonna try to get around just with the cli then.
There are a few commands i need, not only clone but nothing too complicated.
Thanks

2024-07-14 15:44 UTC, DaniPopes requested changes

2024-07-14 15:44 UTC, DaniPopes commented on crates/config/src/soldeer.rs
> +    pub commit: Option<String>,
this can be `rev` like in cargo, which can be a commit or a tag

2024-07-14 15:44 UTC, DaniPopes commented on crates/forge/tests/cli/soldeer.rs
> +    assert_eq!(foundry_contents, actual_foundry_contents);
We've recently updated our test suite, you should use `assert_data_eq!(read_file_to_string(x), str![[""]])` and then run the test to update the assertion automatically.

2024-07-14 15:44 UTC, DaniPopes commented on crates/forge/bin/cmd/soldeer.rs
> +    forge soldeer install [DEPENDENCY]~[VERSION] <GIT_URL> <COMMIT>
same here, the CLI options should probably mimic the config keys, so `--rev`

2024-07-15 14:56 UTC, mario-eth commented
@DaniPopes 
Solved all the comments:
https://github.com/mario-eth/soldeer/pull/98

2024-07-15 15:46 UTC, DaniPopes approved these changes

2024-07-15 20:53 UTC, mattsse approved these changes

2024-07-15 20:53 UTC, merged