extended JsonResult structure
foundry-rs/foundry pull request #8565
Opened 2024-07-30 15:47 UTC by francesco-gaglione

## Motivation
Fixes #7817 

## Solution
Extendend `JsonResult` struct

2024-07-30 18:08 UTC, mattsse approved these changes
lgtm, pending @zerosnacks

2024-07-30 18:39 UTC, DaniPopes commented
Can't we just reuse `result` directly which also implements serde?

2024-07-30 19:16 UTC, francesco-gaglione commented
> Can't we just reuse `result` directly which also implements serde?

Can you explain it better? Sorry, first contribution here, I'm still studying this project

2024-07-30 19:20 UTC, francesco-gaglione commented
Other quesiton, should this change must be stated in the documentation?

2024-07-31 07:36 UTC, zerosnacks requested changes
Thanks for your PR! One small note

I don't think it is necessary to document this extensively given that the changes are additive and non-breaking. Users should be able to rely on the existence of certain keys but not that the entire JSON object remains as is or its size is consistent.

2024-07-31 07:36 UTC, zerosnacks commented on crates/script/src/lib.rs
> +    breakpoints: Breakpoints,
I don't think it is necessary to include `breakpoints` here

2024-07-31 11:15 UTC, DaniPopes commented
> > Can't we just reuse `result` directly which also implements serde?
> 
> Can you explain it better? Sorry, first contribution here, I'm still studying this project.
> 
> Sorry for editing... I checked now understand...
> 
> Probably we can't for this reason:
> 
> `returns: self.execution_artifacts.returns.clone(),`
> 
> that is not included in `result`, so if this is important I think we cannot use `result`

You can keep the existing fields, and just add a `result` field

2024-07-31 19:11 UTC, francesco-gaglione commented
@DaniPopes  `TestResult` is out of the crate and importing the forge crate conduct to a circular dependency. So I think we cannot use `TestResult`

2024-07-31 20:25 UTC, zerosnacks approved these changes

2024-08-08 12:39 UTC, DaniPopes approved these changes

2024-08-08 12:53 UTC, merged