fix(anvil): fix incorrect op-stack deposit tx hashes
foundry-rs/foundry pull request #8567
Opened 2024-07-30 20:52 UTC by jakim929

## Motivation
tx hash calculation for deposit tx for `anvil --optimism` was different from [specs](https://specs.optimism.io/protocol/deposits.html#the-deposited-transaction-type). this made it difficult to deterministically generate the L2 tx hash from the L1 deposit transaction.

- the EIP-2718 tx type was not included when calculating hash
- encoding was slightly different from [spec](https://specs.optimism.io/protocol/deposits.html#the-deposited-transaction-type) 
    - nonce was included in the rlp encoding
    - order of fields was different from spec
## Solution
- calculate tx hash after encoding in eip-2718 envelope format
- fix order of fields / remove nonce when RLP encoding / decoding
- added tests - checks against a op-sepolia tx hash / fields to make sure that the hash / encoding is consistent

2024-07-30 21:00 UTC, mattsse requested changes
this is great, ty

few pedantic nits

we now have this type also here  https://github.com/alloy-rs/op-alloy so we could replace the entire anvil deposit type, will track this separately.

q, are you using eth_sendraw deposit txs at OP for testing?

2024-07-30 21:23 UTC, jakim929 commented on crates/anvil/core/src/eth/transaction/optimism.rs
> +        let mut encoded = Vec::<u8>::new();
will fix!

2024-07-30 21:24 UTC, jakim929 commented on crates/anvil/core/src/eth/transaction/optimism.rs
> +        buf.advance(1);
added!

2024-07-30 21:29 UTC, jakim929 commented
thanks for the quick review! 🙏  addressed the requested changes

> q, are you using eth_sendraw deposit txs at OP for testing?

Yep, it's very useful for testing bridging! and we're using it pretty extensively for https://github.com/ethereum-optimism/supersim , which is a local environment for testing L1 + multiple L2s (anvils) for bridging, message passing etc.

Also we're happy to help maintain the optimism related features on anvil including tasks like
> we now have this type also here https://github.com/alloy-rs/op-alloy so we could replace the entire anvil deposit type, will track this separately.

and improving support for deposit tx validation in the tx pool.

2024-07-31 10:10 UTC, mattsse approved these changes

2024-07-31 10:11 UTC, merged