Config parse auth
foundry-rs/foundry pull request #8570
Opened 2024-07-30 23:23 UTC by caiquejjx

## Motivation
Closes #8276 

## Solution
Adds the auth field to RPCEndpointConfig

2024-07-31 09:46 UTC, zerosnacks commented on crates/config/src/lib.rs
> -                            )))
Nit: please undo the inserted `;`

See: https://github.com/foundry-rs/foundry/blob/master/CONTRIBUTING.md#resolving-an-issue for the linter settings (we are using `nightly` fmt and `nightly` clippy)

2024-07-31 09:47 UTC, zerosnacks commented
Thanks for your PR! Small note on the unintended formatting diff

2024-07-31 22:07 UTC, caiquejjx commented
done, thanks @zerosnacks

2024-07-31 22:09 UTC, mattsse requested changes
great start,

we can expect that this will be used via some env var or similar so we should add support for resolving env vars

see for ref

https://github.com/foundry-rs/foundry/blob/c99854277c346fa6de7a8f9837230b36fd85850e/crates/config/src/endpoints.rs#L117-L131

and

https://github.com/foundry-rs/foundry/blob/c99854277c346fa6de7a8f9837230b36fd85850e/crates/config/src/endpoints.rs#L150-L160

2024-08-02 22:11 UTC, caiquejjx commented
@mattsse I have implemented the auth as an enum similar to the `RpcEndpoint`, lmk you thoughts

2024-08-02 22:32 UTC, mattsse requested changes
nice, would love to see some additional tests like

https://github.com/foundry-rs/foundry/blob/cce36f85c80946bd4a1868411aa99eda879a0e43/crates/config/src/lib.rs#L3369-L3369

2024-08-02 22:32 UTC, mattsse commented on crates/config/src/endpoints.rs
> +    Token(String),
```suggestion
    Raw(String),
```

2024-08-05 14:51 UTC, caiquejjx commented
@mattsse I added a test for checking the resolving of the auth and I also added the `auths` field to the `ResolvedRpcEndpoint` as a way of resolving the auth, its probably not the most optimal solution but is the one that requires less changes on existing code. I can also create a new type for the `config.resolve` result where I can add the auth for an endpoint but let me know what you think

2024-08-08 13:37 UTC, mattsse approved these changes
cool, nice work.

next up we'd find a way to integrate this properly

I think the entrypoint for this would be:

https://github.com/foundry-rs/foundry/blob/master/crates/cli/src/utils/mod.rs#L92-L92

2024-08-08 14:09 UTC, mattsse commented
failing tests unrelated

2024-08-08 14:09 UTC, merged