feat(`cast interface`): allow retrieving abi from contract name
foundry-rs/foundry pull request #8585
Opened 2024-08-02 09:09 UTC by leovct

## Motivation

Closes #8580 

The goal of this PR is to enable the retrieval of interfaces from a local contract without requiring the full path. It achieves this by fetching the artifact from the compiled contract located in the `out/` directory.

Additionally, this PR improves code readability by refactoring the implementation, separating functionalities such as loading ABI from a file, artifact, or Etherscan into distinct functions.

## Testing

### New Feature

Load ABI from local contract without having to specify the full path.

```bash
cast interface ERC20
cast interface contracts/token/ERC20/ERC20.sol:ERC20
```

Before:

```bash
Error:
invalid path or address

Context:
- Odd number of digits
```

After:

```bash
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.4;

interface ERC20 {
    error ERC20InsufficientAllowance(address spender, uint256 allowance, uint256 needed);
    error ERC20InsufficientBalance(address sender, uint256 balance, uint256 needed);
    error ERC20InvalidApprover(address approver);
    error ERC20InvalidReceiver(address receiver);
    error ERC20InvalidSender(address sender);
    error ERC20InvalidSpender(address spender);

    event Approval(address indexed owner, address indexed spender, uint256 value);
    event Transfer(address indexed from, address indexed to, uint256 value);

    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 value) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
    function decimals() external view returns (uint8);
    function name() external view returns (string memory);
    function symbol() external view returns (string memory);
    function totalSupply() external view returns (uint256);
    function transfer(address to, uint256 value) external returns (bool);
    function transferFrom(address from, address to, uint256 value) external returns (bool);
}
```

### Regression Tests

Load ABI from file using full path.

```bash
cast interface ./out/ERC20.sol/ERC20.json
cast interface --name TestERC20 ./out/ERC20.sol/ERC20.json
```

<details>
<summary>Expand to see details</summary>

```bash
$ cast interface ./out/ERC20.sol/ERC20.json
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.4;

interface Interface {
    error ERC20InsufficientAllowance(address spender, uint256 allowance, uint256 needed);
    error ERC20InsufficientBalance(address sender, uint256 balance, uint256 needed);
    error ERC20InvalidApprover(address approver);
    error ERC20InvalidReceiver(address receiver);
    error ERC20InvalidSender(address sender);
    error ERC20InvalidSpender(address spender);

    event Approval(address indexed owner, address indexed spender, uint256 value);
    event Transfer(address indexed from, address indexed to, uint256 value);

    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 value) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
    function decimals() external view returns (uint8);
    function name() external view returns (string memory);
    function symbol() external view returns (string memory);
    function totalSupply() external view returns (uint256);
    function transfer(address to, uint256 value) external returns (bool);
    function transferFrom(address from, address to, uint256 value) external returns (bool);
}
```

```bash
$ cast interface --name TestERC20 ./out/ERC20.sol/ERC20.json
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.4;

interface TestERC20 {
    error ERC20InsufficientAllowance(address spender, uint256 allowance, uint256 needed);
    error ERC20InsufficientBalance(address sender, uint256 balance, uint256 needed);
    error ERC20InvalidApprover(address approver);
    error ERC20InvalidReceiver(address receiver);
    error ERC20InvalidSender(address sender);
    error ERC20InvalidSpender(address spender);

    event Approval(address indexed owner, address indexed spender, uint256 value);
    event Transfer(address indexed from, address indexed to, uint256 value);

    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 value) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
    function decimals() external view returns (uint8);
    function name() external view returns (string memory);
    function symbol() external view returns (string memory);
    function totalSupply() external view returns (uint256);
    function transfer(address to, uint256 value) external returns (bool);
    function transferFrom(address from, address to, uint256 value) external returns (bool);
}
```

</details>

Load ABI from Etherscan.

```bash
erc20_contract="0xbC8E35221904F61b4200Ca44a08e4daC387Ac83A"
cast interface --etherscan-api-key <api-key> "$erc20_contract"
```

<details>
<summary>Expand to see details</summary>

```bash
$ erc20_contract="0xbC8E35221904F61b4200Ca44a08e4daC387Ac83A" cast interface --etherscan-api-key <api-key> "$erc20_contract"
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.4;

interface BlackErc20 {
    event Approval(address indexed owner, address indexed spender, uint256 value);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);
    event Transfer(address indexed from, address indexed to, uint256 value);

    function _deplyAddress() external view returns (address);
    function _devAddress() external view returns (address);
    function _maxMintCount() external view returns (uint256);
    function _maxMintPerAddress() external view returns (uint256);
    function _mintCounts(address) external view returns (uint256);
    function _mintPrice() external view returns (uint256);
    function _mintedCounts() external view returns (uint256);
    function _vitalikAddress() external view returns (address);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
    function decimals() external view returns (uint8);
    function decreaseAllowance(address spender, uint256 subtractedValue) external returns (bool);
    function devAward() external;
    function increaseAllowance(address spender, uint256 addedValue) external returns (bool);
    function lpContract() external view returns (address);
    function mint(uint256 mintCount, address receiveAds) external payable;
    function name() external view returns (string memory);
    function owner() external view returns (address);
    function renounceOwnership() external;
    function setLPContract(address lp) external;
    function symbol() external view returns (string memory);
    function totalSupply() external view returns (uint256);
    function transfer(address to, uint256 amount) external returns (bool);
    function transferFrom(address from, address to, uint256 amount) external returns (bool);
    function transferOwnership(address newOwner) external;
    function wethAddress() external view returns (address);
}
```

</details>

2024-08-02 14:50 UTC, zerosnacks commented
Thanks @leovct! Looks good

cc @klkvr

2024-08-02 16:04 UTC, mattsse requested changes
cool!

could we add another test case like

https://github.com/foundry-rs/foundry/blob/master/crates/cast/tests/cli/main.rs#L881-L881

that fetches the weth interfaces for example

we can check the stderr output and skip in case etherscan is flaky

2024-08-05 08:05 UTC, leovct commented
> cool!
> 
> could we add another test case like
> 
> https://github.com/foundry-rs/foundry/blob/master/crates/cast/tests/cli/main.rs#L881-L881
> 
> that fetches the weth or 0xbC8E35221904F61b4200Ca44a08e4daC387Ac83A for example
> 
> we can check the stderr output and skip in case etherscan is flaky

just added the test! I've created a new Etherscan API key for this, perhaps you'd like to change the value?

2024-08-06 12:36 UTC, mattsse approved these changes

2024-08-06 12:49 UTC, merged