feat: `vm.publicKeyP256`
foundry-rs/foundry pull request #8679
Opened 2024-08-15 16:50 UTC by klkvr

## Motivation

Adds cheatcode for deriving public key for P256 private key

## Solution

2024-08-15 18:43 UTC, DaniPopes requested changes

2024-08-15 18:43 UTC, DaniPopes commented on crates/cheatcodes/spec/src/vm.rs
> +    /// Signs `digest` with `privateKey` using the secp256r1 curve.
wrong doc

2024-08-15 18:43 UTC, DaniPopes commented on crates/cheatcodes/src/crypto.rs
> +fn validate_private_key<C: ecdsa::PrimeCurve>(private_key: &U256) -> Result<()> {
we could pass either C by value to use Debug or a &str parameter for the name of the curve, to use in the error message

2024-08-15 19:18 UTC, mattsse reviewed
lgtm, pending doc nit

2024-08-15 19:24 UTC, DaniPopes approved these changes

2024-08-15 19:48 UTC, merged

2024-08-18 15:03 UTC, pcaversaccio commented
Can you please add the function to the `vm` interface in `forge-std`, otherwise hard to use 🙃