chore(deps): bump alloy
foundry-rs/foundry pull request #8771
Opened 2024-08-29 11:55 UTC by yash-atreya

## Motivation

New version of alloy has been released.

## Solution

Bump alloy to 0.3

2024-09-02 12:32 UTC, onbjerg approved these changes

2024-09-02 12:57 UTC, klkvr commented on crates/common/fmt/src/ui.rs
> +yParity              {}",
We should still format additional fields, I think we can just impl `UIfmt` for `WithOtherFields<Transaction>`?

2024-09-04 15:03 UTC, mattsse commented
what's missing here?

2024-09-04 18:22 UTC, yash-atreya commented
> There's still some work to do
> 
> 
> 
> Merged in https://github.com/foundry-rs/foundry/pull/8627 which includes updated for alloy-core
> 
> 
> 
> Leaving it up to you @yash-atreya 

Yeah

2024-09-04 18:24 UTC, DaniPopes commented on crates/evm/core/src/opts.rs
> +    pub async fn fork_evm_env<N: Network>(
N is not used

2024-09-04 18:24 UTC, DaniPopes commented on crates/evm/core/src/fork/init.rs
> +    let block: <N as Network>::BlockResponse = if let Some(block) = block {
type hint unnecessary

2024-09-05 13:31 UTC, mattsse commented
can we allow evmole in deny.toml for now, we shouldn't block this pr

2024-09-05 13:36 UTC, mattsse requested changes
nit

ptal @klkvr

2024-09-05 13:36 UTC, mattsse commented on crates/anvil/Cargo.toml
> +op-alloy-rpc-types = "0.2.8"
please move to workspace, all of alloy deps should be workspace levle

2024-09-05 13:36 UTC, mattsse commented on crates/anvil/core/src/eth/transaction/optimism.rs
ah followup task would be to replace this with the alloy type

2024-09-05 14:29 UTC, cdump commented
I've released evmole 0.5.0 with updated alloy. A small patch was required for foundry-rs - https://github.com/cdump/evmole/issues/13#issuecomment-2331832673

I haven't created a PR here because of a lot of Cargo.lock changes related to the alloy upgrade, so it's better to apply it in this existing PR

2024-09-06 03:09 UTC, klkvr requested changes

2024-09-06 03:09 UTC, klkvr commented on crates/anvil/src/eth/otterscan/api.rs
> +            }
ots types have tx and block generics too, we should update `build_ots_block_tx` instead

2024-09-06 03:09 UTC, klkvr commented on crates/common/fmt/src/ui.rs
> +        // let block: WithOtherFields<Block> = WithOtherFields::new(block);
```suggestion
```

2024-09-06 13:52 UTC, DaniPopes commented
Released alloy-core 0.8.1 https://github.com/alloy-rs/core/releases/tag/v0.8.1

2024-09-06 14:26 UTC, DaniPopes approved these changes

2024-09-06 14:27 UTC, DaniPopes commented on crates/anvil/src/eth/api.rs
>  pub const CLIENT_VERSION: &str = concat!("anvil/v", env!("CARGO_PKG_VERSION"));
```suggestion
pub const CLIENT_VERSION: &str = concat!("anvil/v", env!("CARGO_PKG_VERSION"));

```

2024-09-06 14:39 UTC, mattsse approved these changes

2024-09-06 14:59 UTC, klkvr approved these changes

2024-09-06 14:59 UTC, merged