fix(cheatcodes): fail when trying to parse malformatted strings as addresses
foundry-rs/foundry pull request #8779
Opened 2024-08-29 23:35 UTC by fmorisan

Hi, I'm here trying to solve #8778.

This is my first time contributing here, and also my first time writing Rust on a real project. Please let me know if the approach I took is wrong here. Thanks!

## Motivation
Fix #8778 as it seemed like a small issue I could take on, and the current behaviour bugged me today as well.

## Solution
Use the already imported `alloy_dyn_abi` crate to try and parse addresses when the passed in `DynSolType` is an address. We do some minimal validation on the passed in string, and handle it with the underlying crate.

2024-08-30 14:33 UTC, klkvr requested changes
The reported issues is about the `parseJson` cheatcode, while your fix is related to typed parsing (e.g. `parseJsonAddress`), which already performs validation in `string::parse_value`. Additionaly, this will break parsing for non-checksummed addresses which is not something we want.

The issue is caused by this code: https://github.com/foundry-rs/foundry/blob/818eeb9d5018d3858238d925fa9c9ef5fcdaee47/crates/cheatcodes/src/json.rs#L572-L575

I think we should not add `0` if string length is 39, and instead throw a error asking user to be explicit on whether this is supposed to be an `address` or `bytes`

2024-08-30 14:52 UTC, fmorisan commented
Alright so we're basically guessing on the underlying type from the string length. Pushed the requested change.

I encountered this issue while using `vm.parseJsonType` as well, though I might have been using an earlier `foundry` version at the time.

2024-08-31 23:39 UTC, klkvr approved these changes

2024-08-31 23:39 UTC, klkvr commented on crates/cheatcodes/src/json.rs
> +                    return Err(format!("Cannot parse \"{val}\" as an address. If you want to specify bytes, prepend zeroes to the value.").into())
```suggestion
                    return Err(format!("Cannot parse \"{val}\" as an address. If you want to specify address, prepend zero to the value.").into())
```

2024-09-01 20:17 UTC, fmorisan commented
accepted the error message suggestion, and rebased to `main` branch tip. thanks!

2024-09-02 23:31 UTC, merged