chore: bump alloy to fix #8830
foundry-rs/foundry pull request #8838
Opened 2024-09-10 09:12 UTC by yash-atreya

## Motivation

Fixes #8830 

## Solution

Bumps alloy to include https://github.com/alloy-rs/alloy/pull/1261

Consequently bump `op-alloy-rpc-types`

2024-09-10 10:57 UTC, mattsse reviewed
this fix is now released

2024-09-10 11:09 UTC, yash-atreya commented
> this fix is now released

Patch removed

2024-09-10 11:42 UTC, mattsse requested changes
nits

2024-09-10 11:42 UTC, mattsse commented on Cargo.toml
> -# https://github.com/alloy-rs/alloy/pull/1229 + https://github.com/alloy-rs/alloy/pull/1243
lets keep them as comments because we'll need them again eventually

2024-09-11 08:02 UTC, mattsse approved these changes

2024-09-11 08:02 UTC, merged