feat(`forge vb`): --ignore-immutables
foundry-rs/foundry pull request #8850
Opened 2024-09-12 10:00 UTC by yash-atreya

## Motivation

Closes #8849 

## Solution

- [x] Get immutable references for both local `deployed_bytecode` and `onchain_runtime_code` using the offsets provided under `immutableReferences` in the artifact. 
- [ ] Extract these references/slices from the bytecode

2024-10-10 14:04 UTC, klkvr requested changes

2024-10-10 14:04 UTC, klkvr commented on crates/verify/src/utils.rs
> +            bytecode = Bytes::from(start_section_vec);
we should account for bytecode being shifted on every iteration, thus requiring next offsets to be shifted too

2024-10-10 14:04 UTC, klkvr commented on crates/verify/src/utils.rs
> +}
nit: can we make this just return a `Vec` of `(start, end)` tuples so that we can just iterate over offsets in `extract_immutable_refs`

2024-12-19 12:06 UTC, yash-atreya commented
closing as stale

2024-12-19 12:06 UTC, closed without merging