feat(randomBytes): adding support to generate different bytes via RngCore
foundry-rs/foundry pull request #8996
Opened 2024-10-01 07:09 UTC by Abhishekkochar

…Core

 fixes #8805 

## Motivation

## Solution

2024-10-01 13:07 UTC, DaniPopes commented
vm.randomBytes already exists

2024-10-01 13:08 UTC, DaniPopes requested changes

2024-10-01 13:08 UTC, DaniPopes commented on crates/cheatcodes/src/utils.rs
> +// Random 8 bytes
There is no need for these comments.

2024-10-01 13:08 UTC, DaniPopes commented on testdata/cheats/Vm.sol
Please revert changes to this file that are not automatically generated.

2024-10-01 13:08 UTC, DaniPopes commented on crates/cheatcodes/spec/src/vm.rs
> +    function randomBytes8() external view returns (bytes8);
Please move to below `randomBytes`

2024-10-01 13:08 UTC, DaniPopes commented on crates/cheatcodes/spec/src/vm.rs
> + }
```suggestion
}
```

2024-10-01 13:10 UTC, StackOverflowExcept1on commented
@DaniPopes yes, but we need new `randomBytes` that works exactly like `rng.fill_bytes` and doesn't generate random `U256`

2024-10-03 11:00 UTC, mattsse approved these changes
these make sense as additional utils imo

2024-10-03 12:15 UTC, DaniPopes approved these changes

2024-10-03 12:29 UTC, merged