fix: include `traces` field when running `forge test -vvvv --json`
foundry-rs/foundry pull request #9034
Opened 2024-10-04 16:12 UTC by zerosnacks

## Motivation

Closes: https://github.com/foundry-rs/foundry/issues/6922

## Solution

Enable and includes traces in JSON output when `forge test` is ran with `--json` enabled (and verbosity >= 3)

Includes Snapbox tests

2024-10-04 16:35 UTC, grandizzy approved these changes
lgtm

2024-10-04 19:59 UTC, DaniPopes requested changes

2024-10-04 19:59 UTC, DaniPopes commented on crates/forge/tests/cli/test_cmd.rs
> +        .stdout_eq(file!["../fixtures/SimpleContractTestNonVerbose.json"]);
```suggestion
        .stdout_eq(file!["../fixtures/SimpleContractTestNonVerbose.json"; Json]);
```

2024-10-04 19:59 UTC, DaniPopes commented on crates/forge/tests/cli/test_cmd.rs
> +        .stdout_eq(file!["../fixtures/SimpleContractTestVerbose.json"]);
```suggestion
        .stdout_eq(file!["../fixtures/SimpleContractTestVerbose.json"; Json]);
```

2024-10-04 19:59 UTC, DaniPopes commented on crates/forge/tests/cli/test_cmd.rs
> +    prj.clear();
use `forgetest!` without init if you're not going to use the initial project layout, we should go through existing tests to check for this too

2024-10-05 12:01 UTC, mattsse approved these changes
nice, pending nits

2024-10-07 14:07 UTC, DaniPopes approved these changes

2024-10-07 14:07 UTC, merged