fix for issue #9095
foundry-rs/foundry pull request #9096
Opened 2024-10-11 12:52 UTC by pogobounce

## Motivation

On some chains with fast block times and/or relatively high latency providers, running a deployment script with `--broadcast` that sends a sequence of transactions can lead to the script failing, as the RPC will report an older nonce for the EOA.

## Solution

If the RPC is out of sync with the current nonce, there's two options:

If it returns a nonce that is ahead, it likely means that the EOA executed some other transaction meanwhile, so the script should stop. 

However, if the nonce is ahead, the culprit is likely a slow RPC. In that case, it makes sense to continue to proceed with the transaction sequence.

Treating these two cases separately means the sequence of transactions won't get stopped out.

2024-10-12 13:26 UTC, klkvr requested changes
provider reporting nonce which is behind might mean several things — there might've been a reorg or node might just still be updating state even though block with previous nonce was already included but `latest` state is not yet updated

in both cases we'd want to wait until we are sure that previous transaction is available in state because otherwise estimate_gas below might fail

let's add a loop here which would do several attempts at fetching and comparing nonce with some delay, and if after eg 5 iterations we still have a mismatch we'd always fail

2024-10-13 18:43 UTC, klkvr requested changes
nice, a couple nits

2024-10-13 18:43 UTC, klkvr commented on crates/script/src/broadcast.rs
> +                        std::thread::sleep(std::time::Duration::from_millis(1000));
this should be `tokio::time::sleep`

2024-10-13 18:43 UTC, klkvr commented on crates/script/src/broadcast.rs
> +                        // Nonces are equal, we can proceed
shouldn't we break here?

2024-10-14 07:34 UTC, pogobounce commented on crates/script/src/broadcast.rs
> +                        // Nonces are equal, we can proceed
you're right, changed

2024-10-14 12:19 UTC, klkvr approved these changes

2024-10-14 12:32 UTC, merged