feat: introduce global thread pool and rename `ShellOtps` to `GlobalOpts`
foundry-rs/foundry pull request #9313
Opened 2024-11-13 14:53 UTC by zerosnacks

## Motivation

Closes: https://github.com/foundry-rs/foundry/issues/8408

## Solution

- Introduces global Rayon thread pool spawned by passing the `--jobs` flag. If not passed it is not spawned. If passed as `--jobs 0` it will use the default Rayon configuration (number of logical CPUs).
- Renames `ShellOpts` to `GlobalOpts`.
- Only selectively passes down `GlobalOpts` where required, this can be the case when wanting to indicate a `conflicts_with` a global argument or you need access to the thread pool. In most cases when checking against the shell configuration it is probably easier to use the e.g. `shell::is_json` variant over passing it all the way down.

2024-11-14 11:05 UTC, grandizzy requested changes
impl looks good! there's a regression re the way rayon thread pool is spawned though, a command like
```
forge test --show-progress --jobs 3
```
always fail now with `Error: The global thread pool has already been initialized.`

while the cast create2 is operating on single thread now instead all available
```
cast create2 --starts-with dead --case-sensitive --deployer 0x0000000000FFe8B47B3e2130213B802212439497 --init-code-hash 0x0c591f26891d6443cf08c5be3584c1e6ae10a4c2f07c5c53218741e9755fb9cd
```
shows always
```
Starting to generate deterministic contract address with 1 threads...
```
whereas on master is 16 for me.

Probably this one should also follow the config
https://github.com/foundry-rs/foundry/blob/a65a5b1445ba7ec9b10baf7ecb28f7a65bbb13ce/crates/cast/src/lib.rs#L2062-L2063

2024-11-14 11:57 UTC, zerosnacks commented
> impl looks good! there's a regression re the way rayon thread pool is spawned though, a command like

Thanks, good catch! Fixed

> I think we should keep the current behavior, that is if `--jobs` flag not passed then we use rayon default (the number of CPUs available) instead single thread.

I had implemented it this way to avoid spawning the global thread pool as the vast majority of commands are not multi-threaded, cc @DaniPopes should we spawn by default?

2024-11-14 12:03 UTC, zerosnacks commented on crates/forge/bin/cmd/test/mod.rs
> -        }
we should indeed spawn the default threads here, this is incorrect

2024-11-14 12:06 UTC, DaniPopes commented on crates/cast/bin/cmd/create2.rs
> -        for i in 0..n_threads {
Shouldn't change this, rayon has some overhead here

2024-11-14 12:06 UTC, DaniPopes commented on crates/cli/src/opts/global.rs
> +        }
This is actually the opposite, it caps at 2; this was just to reduce pressure on tests in cast create2, should keep it there

2024-11-15 06:35 UTC, grandizzy commented
wonder how (if) this would also affect the threadpools spawned in deps (and if we want to or not) like compilers

https://github.com/foundry-rs/compilers/blob/034ecd611eef030217c4b363a794226cd50b4b9e/crates/compilers/src/compile/project.rs#L529-L530

2024-11-20 13:06 UTC, zerosnacks commented
Decided to remove the global thread pool for now and renamed https://github.com/foundry-rs/foundry/issues/8408 as a follow-up to add it

2024-11-20 13:53 UTC, DaniPopes approved these changes

2024-11-20 13:55 UTC, grandizzy approved these changes
lgtm!

2024-11-20 14:16 UTC, merged