fix(anvil): ipc append a newline
foundry-rs/foundry pull request #9608
Opened 2024-12-31 02:35 UTC by 9547

Fix https://github.com/foundry-rs/foundry/issues/9203

## Motivation

As reth will append a `\n` at the end of the stream: 

```rust
impl Default for Separator {
    fn default() -> Self {
        Self::Byte(b'\n')
    }
}

impl tokio_util::codec::Encoder<String> for StreamCodec {
    type Error = io::Error;

    fn encode(&mut self, msg: String, buf: &mut BytesMut) -> io::Result<()> {
        let mut payload = msg.into_bytes();
        if let Separator::Byte(separator) = self.outgoing_separator {
            payload.push(separator);
        }
        buf.extend_from_slice(&payload);
        Ok(())
    }
}
```

https://github.com/paradigmxyz/reth/blob/343bee568fa8f496a07e8849cb5dad726ba15f41/crates/rpc/ipc/src/stream_codec.rs#L44-L48

https://github.com/paradigmxyz/reth/blob/343bee568fa8f496a07e8849cb5dad726ba15f41/crates/rpc/ipc/src/stream_codec.rs#L128-L139

## Solution

2025-01-02 13:43 UTC, 9547 commented
@grandizzy could you please take a look at this one, thanks.

2025-01-02 16:54 UTC, mattsse requested changes
this seems okay and should fix clients that expect a newline and most clients simply skip 0x0A == \n

smol nit

2025-01-02 16:54 UTC, mattsse commented on crates/anvil/server/src/ipc.rs
> +        buf.extend_from_slice(b"\n");
this use put_u8 I think

2025-01-03 09:39 UTC, zerosnacks commented
Thanks @9547!

Proposed change looks good. Added a `likely-breaking` label so this shows up as a potential breaking change in the changelog.

2025-01-03 10:06 UTC, mattsse approved these changes

2025-01-03 10:07 UTC, mattsse commented
ci failures unrelated

2025-01-03 10:07 UTC, merged