feat(foundryup): add foundryup self-update
foundry-rs/foundry pull request #9609
Opened 2024-12-31 03:46 UTC by 9547

## Motivation

Add a `--self-update` command to update foundryup itself.

## Solution

2025-01-02 09:46 UTC, zerosnacks commented on foundryup/foundryup
> +        ;;
I think we can simply use `update` here, mirroring `rustup`, please use the formatting and handling of the other cases

2025-01-02 09:47 UTC, zerosnacks commented on foundryup/foundryup
> +    --self-update   Update foundryup to the latest version
this can be `-U, --update`

2025-01-02 09:48 UTC, zerosnacks commented on foundryup/foundryup
> +  BIN_PATH="$FOUNDRY_BIN_DIR/foundryup"
this should be defined as globals at the top

2025-01-03 09:23 UTC, zerosnacks commented
Thanks @9547!

cc @grandizzy what do you think of adding this into the installer?

It would make upgrading `foundryup` easier for end users and the functionality is in line with `rustup`.

One concern is that where the rest of the Bash script is highly flexible in allowing users to install from forks we would limit `foundryup` to be updated only from the source repo.

Another concern is that it is possible a failure case (e.g. partial download) could possibly brick `foundryup`. One way to address this is to avoid writing directly to the final location, and instead first write to a temporary location, perform a sanity check and then move it to the final location.

cc @sambacha do you have opinions or concerns regarding this proposed update?

2025-01-06 10:36 UTC, grandizzy commented
> One concern is that where the rest of the Bash script is highly flexible in allowing users to install from forks we would limit `foundryup` to be updated only from the source repo. This makes sense from a security standpoint.
> 

Yep, agree is better to update only from the source repo.

> Another concern is that it is possible a failure case (e.g. partial download) could possibly brick `foundryup`. One way to address this is to avoid writing directly to the final location, and instead first write to a temporary location, perform a sanity check and then move it to the final location.
> 

That would be nice to have, though probably unlikely to happen given foundryup size (and could happen also in the current way to update foundryup, by rerunning `curl -L https://foundry.paradigm.xyz | bash`), I don't have a strong opinion if we should add or not.

2025-01-07 18:09 UTC, DaniPopes commented
Downloading to a temp file first is required with bash script because the interpreter (bash) is not guaranteed to buffer the entire file in memory when executing. This means that modifying the file while it's running it could cause inconsistencies and weird errors.

2025-01-08 08:39 UTC, zerosnacks requested changes
per comment above

2025-01-13 13:01 UTC, yash-atreya approved these changes
tested. lgtm!

2025-01-13 13:11 UTC, zerosnacks approved these changes
Tested on MacOS / Linux, wasn't able to create a failure case

2025-01-13 13:43 UTC, merged